from __future__ import annotations

from django.conf import settings

from stable.models import NewsSource, RacingRegion, SourceKind, SourceLanguage, SourceMode, SourceSite, SourceType


BUILTIN_SOURCE_DEFINITIONS = [
    {
        "name": "netkeiba 新着顺",
        "homepage_url": "https://news.netkeiba.com/",
        "feed_url": "https://news.netkeiba.com/?pid=news_backnumber&page=1",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.JAPANESE,
        "racing_region": RacingRegion.JAPAN,
        "source_language": SourceLanguage.JAPANESE,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "netkeiba",
        "source_site": SourceSite.NETKEIBA,
        "source_mode": SourceMode.LATEST,
        "enabled": True,
        "crawl_interval_minutes": 60,
        "notes": "每小时抓取新增新闻；周日重赏时间段 5 分钟一抓。",
        "priority": 100,
    },
    {
        "name": "netkeiba 访问量榜",
        "homepage_url": "https://news.netkeiba.com/",
        "feed_url": "https://news.netkeiba.com/?pid=news_backnumber&rf=access",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.JAPANESE,
        "racing_region": RacingRegion.JAPAN,
        "source_language": SourceLanguage.JAPANESE,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "netkeiba",
        "source_site": SourceSite.NETKEIBA,
        "source_mode": SourceMode.ACCESS,
        "enabled": True,
        "crawl_interval_minutes": 60,
        "notes": "每小时抓取访问量榜前 20 条。",
        "priority": 90,
    },
    {
        "name": "netkeiba 注目数榜",
        "homepage_url": "https://news.netkeiba.com/",
        "feed_url": "https://news.netkeiba.com/?pid=news_backnumber&rf=attention",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.JAPANESE,
        "racing_region": RacingRegion.JAPAN,
        "source_language": SourceLanguage.JAPANESE,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "netkeiba",
        "source_site": SourceSite.NETKEIBA,
        "source_mode": SourceMode.ATTENTION,
        "enabled": True,
        "crawl_interval_minutes": 60,
        "notes": "每小时错峰抓取注目数榜前 20 条。",
        "priority": 80,
    },
    {
        "name": "JRA 官方新闻",
        "homepage_url": "https://www.jra.go.jp/news/",
        "feed_url": "https://www.jra.go.jp/news/",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.JAPANESE,
        "racing_region": RacingRegion.JAPAN,
        "source_language": SourceLanguage.JAPANESE,
        "source_kind": SourceKind.OFFICIAL,
        "adapter_key": "jra",
        "source_site": SourceSite.JRA,
        "source_mode": SourceMode.OFFICIAL,
        "enabled": True,
        "crawl_interval_minutes": 720,
        "notes": "每 12 小时扫描当前月和上月的新稿。",
        "priority": 95,
    },
    {
        "name": "Sponichi 赛马新闻",
        "homepage_url": "https://www.sponichi.co.jp/gamble/",
        "feed_url": "https://www.sponichi.co.jp/gamble/",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.JAPANESE,
        "racing_region": RacingRegion.JAPAN,
        "source_language": SourceLanguage.JAPANESE,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "sponichi",
        "source_site": SourceSite.SPONICHI,
        "source_mode": SourceMode.LATEST,
        "enabled": False,
        "crawl_interval_minutes": 180,
        "notes": "一期国际化候选来源；启用前需用测试抓取确认页面结构。",
        "priority": 70,
    },
    {
        "name": "Sponichi 新闻ランキング",
        "homepage_url": "https://www.sponichi.co.jp/gamble/",
        "feed_url": "https://www.sponichi.co.jp/gamble/ranking/",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.JAPANESE,
        "racing_region": RacingRegion.JAPAN,
        "source_language": SourceLanguage.JAPANESE,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "sponichi",
        "source_site": SourceSite.SPONICHI,
        "source_mode": SourceMode.ACCESS,
        "enabled": False,
        "crawl_interval_minutes": 180,
        "notes": "Sponichi 公开新闻ランキング；页面混有ボート等ギャンブル新闻，适配器只保留赛马相关文章并记录原站排名。",
        "priority": 68,
    },
    {
        "name": "HKJC Racing News",
        "homepage_url": "https://racingnews.hkjc.com/english/",
        "feed_url": "https://racingnews.hkjc.com/english/",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.HONG_KONG,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "hkjc_news",
        "source_site": SourceSite.HKJC_NEWS,
        "source_mode": SourceMode.LATEST,
        "enabled": False,
        "crawl_interval_minutes": 240,
        "notes": "香港英文赛马新闻来源；默认不自动启用。",
        "priority": 65,
    },
    {
        "name": "SCMP Racing",
        "homepage_url": "https://www.scmp.com/sport/racing",
        "feed_url": "https://www.scmp.com/sport/racing",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.HONG_KONG,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "scmp_racing",
        "source_site": SourceSite.SCMP_RACING,
        "source_mode": SourceMode.LATEST,
        "enabled": False,
        "crawl_interval_minutes": 240,
        "notes": "SCMP Racing 英文新闻；默认不自动启用。",
        "priority": 60,
    },
    {
        "name": "Sporting Life Racing",
        "homepage_url": "https://www.sportinglife.com/racing",
        "feed_url": "https://www.sportinglife.com/racing/news",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.UNITED_KINGDOM,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "sporting_life",
        "source_site": SourceSite.SPORTING_LIFE,
        "source_mode": SourceMode.LATEST,
        "enabled": False,
        "crawl_interval_minutes": 240,
        "notes": "英国英文赛马新闻；默认不自动启用。",
        "priority": 55,
    },
    {
        "name": "Sky Sports Racing 新闻",
        "homepage_url": "https://www.skysports.com/racing",
        "feed_url": "https://www.skysports.com/racing/news",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.UNITED_KINGDOM,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "sky_sports_racing",
        "source_site": SourceSite.SKY_SPORTS_RACING,
        "source_mode": SourceMode.LATEST,
        "enabled": False,
        "crawl_interval_minutes": 240,
        "notes": "英国 Sky Sports Racing 新闻列表；默认不自动启用。",
        "priority": 54,
    },
    {
        "name": "Sky Sports Racing Top Stories",
        "homepage_url": "https://www.skysports.com/racing",
        "feed_url": "https://www.skysports.com/racing",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.UNITED_KINGDOM,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "sky_sports_racing",
        "source_site": SourceSite.SKY_SPORTS_RACING,
        "source_mode": SourceMode.ACCESS,
        "enabled": False,
        "crawl_interval_minutes": 240,
        "notes": "Sky Racing 首页 Top Stories / 编辑排序信号；按页面顺序记录 rank，优先于普通新闻列表。",
        "priority": 56,
    },
    {
        "name": "BHA 新闻",
        "homepage_url": "https://www.britishhorseracing.com/",
        "feed_url": "https://www.britishhorseracing.com/press-releases/",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.UNITED_KINGDOM,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.OFFICIAL,
        "adapter_key": "bha",
        "source_site": SourceSite.BHA,
        "source_mode": SourceMode.OFFICIAL,
        "enabled": False,
        "crawl_interval_minutes": 360,
        "notes": "英国官方公告/新闻；默认不自动启用。",
        "priority": 50,
    },
    {
        "name": "France Galop 英文新闻",
        "homepage_url": "https://www.france-galop.com/en/news",
        "feed_url": "https://www.france-galop.com/en/news",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.FRANCE,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.OFFICIAL,
        "adapter_key": "france_galop_news",
        "source_site": SourceSite.FRANCE_GALOP_NEWS,
        "source_mode": SourceMode.OFFICIAL,
        "enabled": False,
        "crawl_interval_minutes": 360,
        "notes": "法国官方英文新闻；只进入英文审核流，不抓法语正文。",
        "priority": 48,
    },
    {
        "name": "TDN France Galop 关键词英文新闻",
        "homepage_url": "https://www.thoroughbreddailynews.com/",
        "feed_url": "https://www.thoroughbreddailynews.com/wp-json/wp/v2/search?search=France%20Galop&per_page=20",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.FRANCE,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "tdn_france",
        "source_site": SourceSite.TDN_FRANCE,
        "source_mode": SourceMode.LATEST,
        "enabled": False,
        "crawl_interval_minutes": 360,
        "notes": "TDN 公开 API 搜索 France Galop 相关英文稿，作为法国英文媒体补充源。",
        "priority": 47,
    },
    {
        "name": "TDN 法国宽关键词英文新闻",
        "homepage_url": "https://www.thoroughbreddailynews.com/",
        "feed_url": "https://www.thoroughbreddailynews.com/wp-json/wp/v2/search?search=French%20racing&per_page=20",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.FRANCE,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "tdn_france_broad",
        "source_site": SourceSite.TDN_FRANCE,
        "source_mode": SourceMode.ACCESS,
        "enabled": False,
        "production_approved": False,
        "crawl_interval_minutes": 360,
        "notes": "TDN 公开 API 多关键词搜索 French racing / ParisLongchamp / Deauville / Chantilly；canonical source site 为 TDN，默认灰度关闭。",
        "priority": 46,
    },
    {
        "name": "At The Races 法国相关英文新闻",
        "homepage_url": "https://www.attheraces.com/",
        "feed_url": "https://www.attheraces.com/news",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.FRANCE,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "at_the_races_france",
        "source_site": SourceSite.AT_THE_RACES,
        "source_mode": SourceMode.LATEST,
        "enabled": False,
        "crawl_interval_minutes": 360,
        "notes": "候选来源；上线前实测列表返回 403，暂不纳入第一版生产来源。",
        "priority": 20,
    },
    {
        "name": "TDN 美国新闻",
        "homepage_url": "https://www.thoroughbreddailynews.com/",
        "feed_url": "https://www.thoroughbreddailynews.com/wp-json/wp/v2/posts?per_page=20",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.UNITED_STATES,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "tdn",
        "source_site": SourceSite.TDN,
        "source_mode": SourceMode.LATEST,
        "enabled": False,
        "crawl_interval_minutes": 240,
        "notes": "美国英文赛马新闻；使用公开 WordPress API 列表，详情页提正文。",
        "priority": 46,
    },
    {
        "name": "Horse Racing Nation 新闻",
        "homepage_url": "https://www.horseracingnation.com/news",
        "feed_url": "https://www.horseracingnation.com/news",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.UNITED_STATES,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "horse_racing_nation",
        "source_site": SourceSite.HORSE_RACING_NATION,
        "source_mode": SourceMode.LATEST,
        "enabled": False,
        "crawl_interval_minutes": 240,
        "notes": "美国 Horse Racing Nation 新闻列表；默认不自动启用。",
        "priority": 44,
    },
    {
        "name": "Horse Racing Nation Trending",
        "homepage_url": "https://www.horseracingnation.com/news",
        "feed_url": "https://www.horseracingnation.com/news",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.UNITED_STATES,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "horse_racing_nation",
        "source_site": SourceSite.HORSE_RACING_NATION,
        "source_mode": SourceMode.ACCESS,
        "enabled": False,
        "crawl_interval_minutes": 240,
        "notes": "Horse Racing Nation Trending/页面排序信号；按页面顺序记录 rank，优先于普通新闻列表。",
        "priority": 45,
    },
    {
        "name": "BloodHorse",
        "homepage_url": "https://www.bloodhorse.com/horse-racing",
        "feed_url": "https://www.bloodhorse.com/horse-racing/articles",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.UNITED_STATES,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "bloodhorse",
        "source_site": SourceSite.BLOODHORSE,
        "source_mode": SourceMode.LATEST,
        "enabled": False,
        "crawl_interval_minutes": 240,
        "notes": "候选来源；上线前实测受 Incapsula/反爬影响，暂不纳入第一版生产来源。",
        "priority": 20,
    },
    {
        "name": "Paulick Report",
        "homepage_url": "https://paulickreport.com/",
        "feed_url": "https://paulickreport.com/news/",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.UNITED_STATES,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.NEWS,
        "adapter_key": "paulick_report",
        "source_site": SourceSite.PAULICK_REPORT,
        "source_mode": SourceMode.LATEST,
        "enabled": False,
        "crawl_interval_minutes": 240,
        "notes": "候选来源；上线前实测列表返回 403，暂不纳入第一版生产来源。",
        "priority": 20,
    },
    {
        "name": "Horse Racing Ireland 新闻",
        "homepage_url": "https://www.hri.ie/news-and-media",
        "feed_url": "https://www.hri.ie/news-and-media",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.IRELAND,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.OFFICIAL,
        "adapter_key": "hri_news",
        "source_site": SourceSite.HRI_NEWS,
        "source_mode": SourceMode.OFFICIAL,
        "enabled": False,
        "production_approved": False,
        "crawl_interval_minutes": 360,
        "notes": (
            "爱尔兰官方新闻候选；automation_permission_status=blocked；"
            "保持关闭且未生产批准。"
        ),
        "priority": 40,
    },
    {
        "name": "Woodbine 新闻",
        "homepage_url": "https://woodbine.com/news/",
        "feed_url": "https://woodbine.com/news/",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.CANADA,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.OFFICIAL,
        "adapter_key": "woodbine_news",
        "source_site": SourceSite.WOODBINE_NEWS,
        "source_mode": SourceMode.OFFICIAL,
        "enabled": False,
        "production_approved": False,
        "crawl_interval_minutes": 360,
        "notes": (
            "加拿大官方赛马场新闻候选；automation_permission_status=blocked；"
            "保持关闭且未生产批准。"
        ),
        "priority": 40,
    },
    {
        "name": "Emirates Racing Authority 新闻",
        "homepage_url": "https://emiratesracing.com/news/",
        "feed_url": "https://emiratesracing.com/news/",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.UNITED_ARAB_EMIRATES,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.OFFICIAL,
        "adapter_key": "emirates_racing_authority",
        "source_site": SourceSite.EMIRATES_RACING_AUTHORITY,
        "source_mode": SourceMode.OFFICIAL,
        "enabled": False,
        "production_approved": False,
        "crawl_interval_minutes": 360,
        "notes": (
            "阿联酋官方新闻候选；automation_permission_status=blocked；"
            "保持关闭且未生产批准。"
        ),
        "priority": 40,
    },
    {
        "name": "Jockey Club of Saudi Arabia 新闻",
        "homepage_url": "https://jcsa.sa/en/news/",
        "feed_url": "https://jcsa.sa/api/news/en/0/12",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.SAUDI_ARABIA,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.OFFICIAL,
        "adapter_key": "jcsa_news",
        "source_site": SourceSite.JCSA_NEWS,
        "source_mode": SourceMode.OFFICIAL,
        "enabled": False,
        "production_approved": False,
        "crawl_interval_minutes": 360,
        "notes": (
            "沙特阿拉伯官方新闻候选；automation_permission_status=unknown；"
            "保持关闭且未生产批准。"
        ),
        "priority": 40,
    },
    {
        "name": "Racing Victoria 新闻",
        "homepage_url": "https://www.racingvictoria.com.au/news",
        "feed_url": "https://www.racingvictoria.com.au/sitemap.xml",
        "source_type": SourceType.BUILTIN,
        "language": SourceLanguage.ENGLISH,
        "racing_region": RacingRegion.AUSTRALIA,
        "source_language": SourceLanguage.ENGLISH,
        "source_kind": SourceKind.OFFICIAL,
        "adapter_key": "racing_victoria_news",
        "source_site": SourceSite.RACING_VICTORIA_NEWS,
        "source_mode": SourceMode.OFFICIAL,
        "enabled": False,
        "production_approved": False,
        "crawl_interval_minutes": 360,
        "notes": (
            "澳大利亚官方新闻候选；automation_permission_status=unknown；"
            "保持关闭且未生产批准。"
        ),
        "priority": 40,
    },
]


def _supported_production_languages() -> set[str]:
    configured = getattr(
        settings,
        "MULTIREGION_SUPPORTED_PRODUCTION_SOURCE_LANGUAGES",
        [SourceLanguage.JAPANESE, SourceLanguage.ENGLISH, SourceLanguage.CHINESE_TRADITIONAL],
    )
    return {str(item).strip() for item in configured if str(item).strip()}


def _prepare_builtin_source_payload(payload: dict) -> dict:
    prepared = dict(payload)
    if prepared.get("source_language") not in _supported_production_languages():
        prepared["production_approved"] = False
        note = prepared.get("notes") or ""
        marker = "source_language_not_supported"
        if marker not in note:
            prepared["notes"] = f"{note}\n{marker}".strip()
    return prepared


def sync_builtin_sources() -> list[NewsSource]:
    sources: list[NewsSource] = []
    protected_fields = {
        "source_site",
        "source_mode",
        "enabled",
        "production_approved",
        "effective_crawl_interval_minutes",
        "backoff_until",
        "manual_pause_reason",
        "failure_streak",
        "success_streak",
        "last_error_category",
        "allow_event_boost",
    }
    for raw_payload in BUILTIN_SOURCE_DEFINITIONS:
        payload = _prepare_builtin_source_payload(raw_payload)
        lookup = {
            "source_site": payload["source_site"],
            "source_mode": payload["source_mode"],
        }
        defaults = {key: value for key, value in payload.items() if key not in lookup}
        source, created = NewsSource.objects.get_or_create(
            **lookup,
            defaults=defaults,
        )
        if not created:
            update_fields = []
            for field_name, value in payload.items():
                if field_name in protected_fields and field_name != "production_approved":
                    continue
                if field_name == "production_approved" and raw_payload.get("source_language") in _supported_production_languages():
                    continue
                if getattr(source, field_name) != value:
                    setattr(source, field_name, value)
                    update_fields.append(field_name)
            if update_fields:
                source.save(update_fields=[*update_fields, "updated_at"])
        sources.append(source)
    return sources


def find_builtin_source(source_site: str, source_mode: str) -> NewsSource | None:
    return (
        NewsSource.objects.filter(
            source_site=source_site,
            source_mode=source_mode,
            deleted_at__isnull=True,
        )
        .order_by("-enabled", "-priority", "id")
        .first()
    )
