# Generated by Django 5.2.1 on 2026-04-06 07:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('group_id', models.CharField(max_length=64, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-is_default', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('started', '运行中'), ('success', '成功'), ('failed', '失败')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('detail', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TermEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_type', models.CharField(choices=[('horse', '马名'), ('race', '赛事'), ('jockey', '骑手'), ('trainer', '练马师'), ('owner', '马主'), ('farm', '牧场'), ('racecourse', '赛马场'), ('org', '机构'), ('fixed_phrase', '固定译法'), ('other', '其他')], default='other', max_length=32)),
                ('source_ja', models.CharField(max_length=255)),
                ('target_zh', models.CharField(max_length=255)),
                ('aliases_ja', models.JSONField(blank=True, default=list)),
                ('aliases_zh', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-priority', 'source_ja'),
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_site', models.CharField(choices=[('netkeiba', 'netkeiba'), ('jra', 'JRA')], max_length=32)),
                ('source_mode', models.CharField(choices=[('latest', '新着順'), ('access', 'アクセス順'), ('attention', '注目数順'), ('official', 'JRA官方')], max_length=32)),
                ('source_article_id', models.CharField(max_length=255)),
                ('title_ja', models.CharField(max_length=500)),
                ('body_ja_raw', models.TextField(blank=True)),
                ('body_ja_normalized', models.TextField(blank=True)),
                ('title_zh', models.CharField(blank=True, max_length=500)),
                ('body_zh', models.TextField(blank=True)),
                ('push_summary_zh', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('source_url', models.URLField(max_length=1000)),
                ('is_first_crawled', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('crawled', '已抓取'), ('translated', '已翻译'), ('reviewed', '已审核'), ('push_ready', '可推送'), ('pushed', '已推送'), ('push_failed', '推送失败')], default='crawled', max_length=32)),
                ('editor_notes', models.TextField(blank=True)),
                ('manually_edited_fields', models.JSONField(blank=True, default=list)),
                ('translation_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-published_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('source_site', 'source_article_id'), name='uq_article_source_article_id')],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_url', models.URLField(max_length=1000)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('caption_ja', models.TextField(blank=True)),
                ('caption_zh', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stable.newsarticle')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='NewsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_site', models.CharField(choices=[('netkeiba', 'netkeiba'), ('jra', 'JRA')], max_length=32)),
                ('source_mode', models.CharField(choices=[('latest', '新着順'), ('access', 'アクセス順'), ('attention', '注目数順'), ('official', 'JRA官方')], max_length=32)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('comment_count', models.PositiveIntegerField(blank=True, null=True)),
                ('attention_count', models.PositiveIntegerField(blank=True, null=True)),
                ('snapshot_metadata', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='stable.newsarticle')),
            ],
            options={
                'ordering': ('-captured_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', '排队中'), ('success', '成功'), ('failed', '失败')], default='queued', max_length=16)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_logs', to='stable.newsarticle')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_push_logs', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_logs', to='stable.pushtarget')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TranslationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=128)),
                ('terms_used', models.JSONField(blank=True, default=list)),
                ('prompt_excerpt', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_runs', to='stable.newsarticle')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
