# Generated by Django 5.2.1 on 2026-04-08 15:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('started', '运行中'), ('success', '成功'), ('failed', '失败')], default='started', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='crawl_status',
            field=models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('ignored', '忽略')], default='success', max_length=16),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='ignored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='original_author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='original_content_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='published_to_web_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='summary_zh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='tags_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='translated_body_zh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='translated_summary_zh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='translated_title_zh',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='workflow_status',
            field=models.CharField(choices=[('pending_translation', '待翻译'), ('translation_failed', '翻译失败'), ('pending_edit', '待编辑'), ('pending_review', '待审核'), ('published', '已发布'), ('rejected', '已驳回'), ('withdrawn', '已撤回'), ('archived', '已归档'), ('ignored', '已忽略')], default='pending_translation', max_length=32),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source_mode',
            field=models.CharField(choices=[('latest', '新着顺'), ('access', '访问量榜'), ('attention', '注目数榜'), ('official', '官方新闻')], max_length=32),
        ),
        migrations.AlterField(
            model_name='newssnapshot',
            name='source_mode',
            field=models.CharField(choices=[('latest', '新着顺'), ('access', '访问量榜'), ('attention', '注目数榜'), ('official', '官方新闻')], max_length=32),
        ),
        migrations.AlterField(
            model_name='termentry',
            name='term_type',
            field=models.CharField(choices=[('horse', '马名'), ('race', '赛事'), ('jockey', '骑手'), ('trainer', '调教师'), ('owner', '马主'), ('farm', '牧场'), ('racecourse', '赛马场'), ('org', '机构'), ('fixed_phrase', '固定译法'), ('other', '其他')], default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='crawl_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='stable.crawljob'),
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_image_url', models.URLField(max_length=1000)),
                ('internal_image_url', models.CharField(blank=True, max_length=1000)),
                ('storage_provider', models.CharField(default='local', max_length=32)),
                ('status', models.CharField(choices=[('ready', '可用'), ('failed', '失败')], default='ready', max_length=16)),
                ('is_cover', models.BooleanField(default=False)),
                ('crop_ratio', models.CharField(blank=True, max_length=32)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='stable.newsarticle')),
                ('source_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='stable.newsimage')),
            ],
            options={
                'ordering': ('-is_cover', 'id'),
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='cover_media_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_articles', to='stable.mediaasset'),
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('homepage_url', models.URLField(max_length=1000)),
                ('feed_url', models.URLField(max_length=1000)),
                ('source_type', models.CharField(choices=[('builtin', '内置适配器'), ('rss', 'RSS'), ('html_list', 'HTML 列表页'), ('article_template', '文章页模板')], default='builtin', max_length=32)),
                ('language', models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文')], default='ja', max_length=8)),
                ('adapter_key', models.CharField(blank=True, max_length=64)),
                ('source_site', models.CharField(blank=True, choices=[('netkeiba', 'netkeiba'), ('jra', 'JRA')], max_length=32)),
                ('source_mode', models.CharField(blank=True, choices=[('latest', '新着顺'), ('access', '访问量榜'), ('attention', '注目数榜'), ('official', '官方新闻')], max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('crawl_interval_minutes', models.PositiveIntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, max_length=1000)),
                ('priority', models.IntegerField(default=0)),
                ('default_tags', models.JSONField(blank=True, default=list)),
                ('last_crawl_at', models.DateTimeField(blank=True, null=True)),
                ('last_crawl_status', models.CharField(blank=True, choices=[('started', '运行中'), ('success', '成功'), ('failed', '失败')], max_length=16)),
                ('last_crawl_message', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-enabled', '-priority', 'name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('source_site', ''), _negated=True), models.Q(('source_mode', ''), _negated=True)), fields=('source_site', 'source_mode'), name='uq_news_source_site_mode_active')],
            },
        ),
        migrations.AddField(
            model_name='crawljob',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_jobs', to='stable.newssource'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='stable.newssource'),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
