# Generated by Django 5.2.1 on 2026-04-09 00:40

from django.db import migrations, models


def backfill_translation_state(apps, schema_editor):
    NewsArticle = apps.get_model("stable", "NewsArticle")
    TranslationRun = apps.get_model("stable", "TranslationRun")

    for article in NewsArticle.objects.all():
        runs = TranslationRun.objects.filter(article_id=article.id).order_by("-created_at", "-id")
        latest_run = runs.first()
        success_run = runs.filter(status="success").first()
        metadata = article.translation_metadata or {}

        updates = {
            "translation_retry_count": max(runs.count() - 1, 0),
            "translation_error_message": "",
            "translation_model": metadata.get("model", ""),
            "translation_provider": metadata.get("provider", ""),
        }

        if success_run:
            updates["translation_status"] = "translated"
            updates["translated_at"] = success_run.updated_at
            updates["translation_model"] = success_run.model_name or updates["translation_model"]
            updates["translation_provider"] = success_run.provider_name or updates["translation_provider"]
        elif latest_run and latest_run.status == "failed":
            updates["translation_status"] = "failed"
            updates["translation_error_message"] = latest_run.error_message or ""
            updates["translation_model"] = latest_run.model_name or updates["translation_model"]
            updates["translation_provider"] = latest_run.provider_name or updates["translation_provider"]
        elif article.translated_title_zh or article.translated_body_zh or article.translated_summary_zh:
            updates["translation_status"] = "translated"
            updates["translated_at"] = article.updated_at
        else:
            updates["translation_status"] = "pending"

        NewsArticle.objects.filter(pk=article.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0003_seed_sources_and_backfill_articles"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="translated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="translation_error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="translation_model",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="translation_provider",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="translation_retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="translation_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="translation_status",
            field=models.CharField(
                choices=[
                    ("pending", "待翻译"),
                    ("translating", "翻译中"),
                    ("translated", "已翻译"),
                    ("failed", "翻译失败"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="translationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "进行中"),
                    ("success", "成功"),
                    ("failed", "失败"),
                ],
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_translation_state, migrations.RunPython.noop),
    ]
