# Generated by Django 5.2.1 on 2026-05-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0004_newsarticle_translated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('crawl_failed', '来源抓取失败'), ('translation_failed', '翻译失败'), ('rewrite_failed', '改写失败'), ('publish_failed', '自动发布失败'), ('stale_source', '来源长时间无新稿'), ('backlog', '候选稿异常堆积'), ('no_auto_publish_24h', '24 小时无自动发布'), ('important_manual', '重点新闻转人工'), ('repeated_failure', '关键任务连续失败')], max_length=32)),
                ('channel', models.CharField(choices=[('email', '邮件'), ('sms', '短信'), ('qq', 'QQ'), ('wechat', '微信')], max_length=16)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('queued', '排队中'), ('sent', '已发送'), ('failed', '失败'), ('skipped', '跳过')], default='queued', max_length=16)),
                ('payload_summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='auto_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='automation_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='automation_status',
            field=models.CharField(choices=[('pending', '待处理'), ('scored', '已评分'), ('rewrite_ready', '待改写'), ('rewritten', '已改写'), ('validated', '已校验'), ('publish_ready', '可自动发布'), ('auto_published', '已自动发布'), ('manual_review_required', '需人工审核'), ('ignored', '已忽略'), ('failed', '自动化失败')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='base_translation_zh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='content_category',
            field=models.CharField(blank=True, choices=[('flash', '快讯'), ('pre_race', '赛前前瞻'), ('post_race', '赛后结果/复盘'), ('official', '官方公告'), ('interview', '采访/人物'), ('other', '其他')], max_length=32),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='decision_reason',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='decision_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='published_by_mode',
            field=models.CharField(blank=True, choices=[('manual', '人工'), ('auto', '自动')], max_length=16),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='quality_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='review_mode',
            field=models.CharField(blank=True, choices=[('auto', '自动发布'), ('manual', '人工审核'), ('ignored', '忽略')], max_length=16),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='rewrite_body_zh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='rewrite_confidence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='rewrite_summary_zh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='rewrite_title_zh',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], max_length=16),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='score_total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(choices=[('score', '评分'), ('rewrite', '改写'), ('validate', '校验'), ('publish', '发布'), ('notify', '通知')], max_length=16)),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('skipped', '跳过')], max_length=16)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='stable.newsarticle')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
