# Generated by Django 5.2.1 on 2026-06-06 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0005_automation_mvp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_type', models.CharField(choices=[('horse', '马名'), ('race', '赛事'), ('jockey', '骑手'), ('trainer', '调教师'), ('owner', '马主'), ('farm', '牧场'), ('racecourse', '赛马场'), ('org', '机构'), ('fixed_phrase', '固定译法'), ('other', '其他')], max_length=32)),
                ('source_ja', models.CharField(max_length=255)),
                ('normalized_key', models.CharField(max_length=255)),
                ('suggested_target_zh', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('ignored', '已忽略'), ('merged', '已合并')], default='pending', max_length=16)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('detection_reasons', models.JSONField(blank=True, default=list)),
                ('conflicts', models.JSONField(blank=True, default=list)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('accepted_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_candidates', to='stable.termentry')),
                ('merged_into_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_candidates', to='stable.termcandidate')),
                ('merged_into_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_candidates', to='stable.termentry')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_term_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen_at', '-confidence', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TermCandidateEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_fields', models.JSONField(blank=True, default=list)),
                ('contexts', models.JSONField(blank=True, default=list)),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('detectors', models.JSONField(blank=True, default=list)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_candidate_evidence', to='stable.newsarticle')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='stable.termcandidate')),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='termcandidate',
            index=models.Index(fields=['status', 'term_type', '-last_seen_at'], name='termcand_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='termcandidate',
            index=models.Index(fields=['-confidence', '-last_seen_at'], name='termcand_conf_seen_idx'),
        ),
        migrations.AddConstraint(
            model_name='termcandidate',
            constraint=models.UniqueConstraint(fields=('term_type', 'normalized_key'), name='uq_term_candidate_type_normalized'),
        ),
        migrations.AddConstraint(
            model_name='termcandidateevidence',
            constraint=models.UniqueConstraint(fields=('candidate', 'article'), name='uq_term_candidate_evidence_article'),
        ),
    ]
