# Generated by Django 5.2.1 on 2026-06-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0006_termcandidate_termcandidateevidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termcandidate',
            name='aliases_ja',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='aliases_zh',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='termcandidate',
            name='target_zh',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='termentry',
            name='race_grade',
            field=models.CharField(blank=True, choices=[('G1', 'G1 / GI / GⅠ'), ('G2', 'G2 / GII / GⅡ'), ('G3', 'G3 / GIII / GⅢ'), ('JPN1', 'Jpn1 / JpnⅠ'), ('JPN2', 'Jpn2 / JpnⅡ'), ('JPN3', 'Jpn3 / JpnⅢ'), ('JG1', 'J-G1 / J・GⅠ'), ('JG2', 'J-G2 / J・GⅡ'), ('JG3', 'J-G3 / J・GⅢ'), ('L', 'Listed / リステッド'), ('OP', 'Open / オープン'), ('3WIN', '3胜级'), ('2WIN', '2胜级'), ('1WIN', '1胜级'), ('NEWCOMER', '新马'), ('MAIDEN', '未胜利'), ('LOCAL_GRADE', '地方重赏'), ('OTHER', '其他')], max_length=32),
        ),
    ]
