# Generated by Django 5.2.1 on 2026-06-23 16:43

import django.db.models.deletion
from django.db import migrations, models


NON_HORSE_FIXED_PHRASES = [
    ("タイトル", "头衔"),
    ("メートル", "米"),
    ("オッズ", "赔率"),
    ("ハンデ", "让磅"),
    ("ラジオ", "广播"),
    ("ダート", "泥地"),
    ("マイル", "一英里"),
    ("スプリント", "短途"),
    ("クラス", "级别"),
    ("チャンス", "机会"),
    ("キャリア", "赛历"),
    ("イメージ", "印象"),
    ("デビュー", "出道"),
    ("ゲート", "闸门"),
]


def seed_non_horse_fixed_phrases(apps, schema_editor):
    TermEntry = apps.get_model("stable", "TermEntry")
    for source_ja, target_zh in NON_HORSE_FIXED_PHRASES:
        term = TermEntry.objects.filter(source_ja=source_ja, term_type="fixed_phrase").first()
        created = False
        if term is None:
            term = TermEntry.objects.create(
                source_ja=source_ja,
                target_zh=target_zh,
                term_type="fixed_phrase",
                priority=20,
                is_active=True,
                notes="non_horse_common_word: 自动发布门禁普通词过滤种子",
            )
            created = True
        if not created:
            changed = False
            if not term.target_zh:
                term.target_zh = target_zh
                changed = True
            if term.term_type != "fixed_phrase":
                term.term_type = "fixed_phrase"
                changed = True
            if "non_horse_common_word" not in (term.notes or ""):
                term.notes = ((term.notes + "\n") if term.notes else "") + "non_horse_common_word: 自动发布门禁普通词过滤种子"
                changed = True
            if changed:
                term.save(update_fields=["target_zh", "term_type", "notes", "updated_at"])


def unseed_non_horse_fixed_phrases(apps, schema_editor):
    TermEntry = apps.get_model("stable", "TermEntry")
    TermEntry.objects.filter(
        source_ja__in=[source_ja for source_ja, _ in NON_HORSE_FIXED_PHRASES],
        notes__icontains="non_horse_common_word",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0008_externaldataimportrun_externaldataimportlock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='automation_warning_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='automation_warning_email_signature',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_articles', to='stable.newsarticle'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='duplicate_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='duplicate_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='gate_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='workflow_status',
            field=models.CharField(choices=[('pending_translation', '待翻译'), ('translation_failed', '翻译失败'), ('pending_edit', '待编辑'), ('pending_review', '待审核'), ('published', '已发布'), ('duplicate', '重复内容'), ('rejected', '已驳回'), ('withdrawn', '已撤回'), ('archived', '已归档'), ('ignored', '已忽略')], default='pending_translation', max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('crawl_failed', '来源抓取失败'), ('translation_failed', '翻译失败'), ('rewrite_failed', '改写失败'), ('publish_failed', '自动发布失败'), ('stale_source', '来源长时间无新稿'), ('backlog', '候选稿异常堆积'), ('no_auto_publish_24h', '24 小时无自动发布'), ('important_manual', '重点新闻转人工'), ('high_value_warning', '高价值新闻 warning'), ('repeated_failure', '关键任务连续失败')], max_length=32),
        ),
        migrations.RunPython(seed_non_horse_fixed_phrases, unseed_non_horse_fixed_phrases),
    ]
