# Generated by Django 5.2.1 on 2026-06-23 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0009_automation_publish_gates'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQPushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', '待推送'), ('retrying', '等待重试'), ('sending', '发送中'), ('sent', '已发送'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('last_error_type', models.CharField(blank=True, choices=[('url_unavailable', '公开 URL 不可访问'), ('send_failed', 'OneBot 发送失败'), ('not_eligible', '不符合推送范围'), ('no_targets', '无启用目标群')], max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('message_id', models.CharField(blank=True, max_length=128)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qq_push_deliveries', to='stable.newsarticle')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qq_push_deliveries', to='stable.pushtarget')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', '-updated_at'], name='qqpush_status_updated_idx'), models.Index(fields=['target', 'status'], name='qqpush_target_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'target'), name='uq_qq_push_delivery_article_target')],
            },
        ),
    ]
