# Generated by Django 5.2.1 on 2026-06-25 12:32

from django.conf import settings
from django.db import migrations, models


def backfill_existing_push_targets_to_japan(apps, schema_editor):
    PushTarget = apps.get_model('stable', 'PushTarget')
    PushTarget.objects.filter(allowed_regions=[]).update(allowed_regions=['japan'])


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0010_qqpushdelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='termcandidate',
            name='uq_term_candidate_type_normalized',
        ),
        migrations.AddField(
            model_name='externaldataimporterror',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AddField(
            model_name='externaldataimporterror',
            name='source_language',
            field=models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], default='ja', max_length=8),
        ),
        migrations.AddField(
            model_name='externaldataimportlock',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AddField(
            model_name='externaldataimportrun',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AddField(
            model_name='externaldataimportrun',
            name='source_language',
            field=models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], default='ja', max_length=8),
        ),
        migrations.AddField(
            model_name='externalhorse',
            name='color',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='externalhorse',
            name='country',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='externalhorse',
            name='horse_name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalhorse',
            name='horse_name_zh_hant',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalhorse',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalhorse',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AddField(
            model_name='externalhorse',
            name='record_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalhorse',
            name='source_language',
            field=models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], default='ja', max_length=8),
        ),
        migrations.AddField(
            model_name='externalhorse',
            name='trainer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalhorsealias',
            name='name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalhorsealias',
            name='name_zh_hant',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalhorsealias',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AddField(
            model_name='externalhorsealias',
            name='source_language',
            field=models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], default='ja', max_length=8),
        ),
        migrations.AddField(
            model_name='externalhorsehistory',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AddField(
            model_name='externalhorsehistory',
            name='source_language',
            field=models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], default='ja', max_length=8),
        ),
        migrations.AddField(
            model_name='externalrace',
            name='going',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='externalrace',
            name='prize_money',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='externalrace',
            name='race_class',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='externalrace',
            name='race_grade',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='externalrace',
            name='race_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='externalrace',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AddField(
            model_name='externalrace',
            name='scheduled_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalrace',
            name='source_language',
            field=models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], default='ja', max_length=8),
        ),
        migrations.AddField(
            model_name='externalrace',
            name='track',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='externalrace',
            name='venue',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='externalraceentry',
            name='barrier',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='externalraceentry',
            name='carried_weight',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='externalraceentry',
            name='equipment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalraceentry',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalraceentry',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AddField(
            model_name='externalraceentry',
            name='rating',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='externalraceentry',
            name='source_language',
            field=models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], default='ja', max_length=8),
        ),
        migrations.AddField(
            model_name='externalraceodds',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AddField(
            model_name='externalraceodds',
            name='source_language',
            field=models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], default='ja', max_length=8),
        ),
        migrations.AddField(
            model_name='externalraceresult',
            name='barrier',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='externalraceresult',
            name='finish_time',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='externalraceresult',
            name='margin',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='externalraceresult',
            name='odds_value',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='externalraceresult',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AddField(
            model_name='externalraceresult',
            name='running_position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalraceresult',
            name='sectional_time',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalraceresult',
            name='source_language',
            field=models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], default='ja', max_length=8),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source_language',
            field=models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], default='ja', max_length=8),
        ),
        migrations.AddField(
            model_name='newssource',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AddField(
            model_name='newssource',
            name='source_kind',
            field=models.CharField(choices=[('news', '新闻'), ('database', '数据库'), ('official', '官方'), ('media', '媒体')], default='news', max_length=32),
        ),
        migrations.AddField(
            model_name='newssource',
            name='source_language',
            field=models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], default='ja', max_length=8),
        ),
        migrations.AddField(
            model_name='pushtarget',
            name='allowed_regions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pushtarget',
            name='importance_strategy',
            field=models.CharField(blank=True, choices=[('', '继承全局默认'), ('ranked', '榜单重点新闻')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='pushtarget',
            name='push_scope',
            field=models.CharField(blank=True, choices=[('', '继承全局默认'), ('all_public', '所有公开新闻'), ('high_value_only', '仅重点新闻')], default='', max_length=32),
        ),
        migrations.RunPython(backfill_existing_push_targets_to_japan, migrations.RunPython.noop),
        migrations.AddField(
            model_name='termcandidate',
            name='source_language',
            field=models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], default='ja', max_length=8),
        ),
        migrations.AddField(
            model_name='termentry',
            name='source_language',
            field=models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], default='ja', max_length=8),
        ),
        migrations.AlterField(
            model_name='externaldataimporterror',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externaldataimportlock',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='externaldataimportrun',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalhorse',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalhorsealias',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalhorsehistory',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalraceentry',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalraceodds',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalraceresult',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source_site',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('jra', 'JRA'), ('sponichi', 'Sponichi'), ('hkjc_news', 'HKJC Racing News'), ('scmp_racing', 'SCMP Racing'), ('sporting_life', 'Sporting Life Racing'), ('bha', 'BHA'), ('at_the_races', 'At The Races'), ('bloodhorse', 'BloodHorse'), ('paulick_report', 'Paulick Report')], max_length=32),
        ),
        migrations.AlterField(
            model_name='newssnapshot',
            name='source_site',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('jra', 'JRA'), ('sponichi', 'Sponichi'), ('hkjc_news', 'HKJC Racing News'), ('scmp_racing', 'SCMP Racing'), ('sporting_life', 'Sporting Life Racing'), ('bha', 'BHA'), ('at_the_races', 'At The Races'), ('bloodhorse', 'BloodHorse'), ('paulick_report', 'Paulick Report')], max_length=32),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='language',
            field=models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], default='ja', max_length=8),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='source_site',
            field=models.CharField(blank=True, choices=[('netkeiba', 'netkeiba'), ('jra', 'JRA'), ('sponichi', 'Sponichi'), ('hkjc_news', 'HKJC Racing News'), ('scmp_racing', 'SCMP Racing'), ('sporting_life', 'Sporting Life Racing'), ('bha', 'BHA'), ('at_the_races', 'At The Races'), ('bloodhorse', 'BloodHorse'), ('paulick_report', 'Paulick Report')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='termcandidate',
            constraint=models.UniqueConstraint(fields=('term_type', 'source_language', 'normalized_key'), name='uq_term_candidate_type_normalized'),
        ),
    ]
