# Generated by Codex on 2026-06-25

from django.db import migrations, models
import django.db.models.deletion


def backfill_term_aliases(apps, schema_editor):
    TermEntry = apps.get_model("stable", "TermEntry")
    TermAlias = apps.get_model("stable", "TermAlias")
    for term in TermEntry.objects.all().iterator():
        language = term.source_language or "ja"
        values = []
        if term.source_ja:
            values.append((term.source_ja, "primary"))
        aliases = term.aliases_ja if isinstance(term.aliases_ja, list) else []
        for alias in aliases:
            values.append((alias, "alias"))
        seen = set()
        for text, alias_type in values:
            normalized = (text or "").strip()
            if not normalized or normalized in seen:
                continue
            seen.add(normalized)
            TermAlias.objects.get_or_create(
                term=term,
                source_language=language,
                text=normalized,
                defaults={"alias_type": alias_type, "is_active": term.is_active},
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0011_remove_termcandidate_uq_term_candidate_type_normalized_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_language",
                    models.CharField(
                        choices=[
                            ("ja", "日文"),
                            ("en", "英文"),
                            ("zh", "中文"),
                            ("zh-hant", "繁体中文"),
                            ("fr", "法语"),
                        ],
                        default="ja",
                        max_length=8,
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "alias_type",
                    models.CharField(
                        choices=[("primary", "主原文名"), ("alias", "原文别名")],
                        default="alias",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_aliases",
                        to="stable.termentry",
                    ),
                ),
            ],
            options={
                "ordering": ("source_language", "alias_type", "text"),
            },
        ),
        migrations.AddConstraint(
            model_name="termalias",
            constraint=models.UniqueConstraint(
                fields=("term", "source_language", "text"),
                name="uq_term_alias_term_language_text",
            ),
        ),
        migrations.AddIndex(
            model_name="termalias",
            index=models.Index(fields=("source_language", "text"), name="idx_termalias_lang_text"),
        ),
        migrations.RunPython(backfill_term_aliases, noop_reverse),
    ]
