# Generated by Django 5.2.1 on 2026-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0012_termalias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='source_site',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('jra', 'JRA'), ('sponichi', 'Sponichi'), ('hkjc_news', 'HKJC Racing News'), ('scmp_racing', 'SCMP Racing'), ('sporting_life', 'Sporting Life Racing'), ('sky_sports_racing', 'Sky Sports Racing'), ('bha', 'BHA'), ('france_galop_news', 'France Galop English News'), ('tdn', 'Thoroughbred Daily News'), ('tdn_france', 'TDN France Keyword News'), ('horse_racing_nation', 'Horse Racing Nation'), ('at_the_races', 'At The Races'), ('bloodhorse', 'BloodHorse'), ('paulick_report', 'Paulick Report')], max_length=32),
        ),
        migrations.AlterField(
            model_name='newssnapshot',
            name='source_site',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('jra', 'JRA'), ('sponichi', 'Sponichi'), ('hkjc_news', 'HKJC Racing News'), ('scmp_racing', 'SCMP Racing'), ('sporting_life', 'Sporting Life Racing'), ('sky_sports_racing', 'Sky Sports Racing'), ('bha', 'BHA'), ('france_galop_news', 'France Galop English News'), ('tdn', 'Thoroughbred Daily News'), ('tdn_france', 'TDN France Keyword News'), ('horse_racing_nation', 'Horse Racing Nation'), ('at_the_races', 'At The Races'), ('bloodhorse', 'BloodHorse'), ('paulick_report', 'Paulick Report')], max_length=32),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='source_site',
            field=models.CharField(blank=True, choices=[('netkeiba', 'netkeiba'), ('jra', 'JRA'), ('sponichi', 'Sponichi'), ('hkjc_news', 'HKJC Racing News'), ('scmp_racing', 'SCMP Racing'), ('sporting_life', 'Sporting Life Racing'), ('sky_sports_racing', 'Sky Sports Racing'), ('bha', 'BHA'), ('france_galop_news', 'France Galop English News'), ('tdn', 'Thoroughbred Daily News'), ('tdn_france', 'TDN France Keyword News'), ('horse_racing_nation', 'Horse Racing Nation'), ('at_the_races', 'At The Races'), ('bloodhorse', 'BloodHorse'), ('paulick_report', 'Paulick Report')], max_length=32),
        ),
    ]
