# Generated by Django 5.2.1 on 2026-07-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0015_termentry_racing_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldataimporterror',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externaldataimportlock',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='externaldataimportrun',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalhorse',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalhorsealias',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalhorsehistory',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalraceentry',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalraceodds',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalraceresult',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
    ]
