# Generated by Django 5.2.1 on 2026-07-01 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0016_alter_externaldataimporterror_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorRaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('racing_region', models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], max_length=32)),
                ('race_grade', models.CharField(choices=[('G1', 'G1 / GI / GⅠ'), ('G2', 'G2 / GII / GⅡ'), ('G3', 'G3 / GIII / GⅢ'), ('JPN1', 'Jpn1 / JpnⅠ'), ('JPN2', 'Jpn2 / JpnⅡ'), ('JPN3', 'Jpn3 / JpnⅢ'), ('JG1', 'J-G1 / J・GⅠ'), ('JG2', 'J-G2 / J・GⅡ'), ('JG3', 'J-G3 / J・GⅢ'), ('L', 'Listed / リステッド'), ('OP', 'Open / オープン'), ('3WIN', '3胜级'), ('2WIN', '2胜级'), ('1WIN', '1胜级'), ('NEWCOMER', '新马'), ('MAIDEN', '未胜利'), ('LOCAL_GRADE', '地方重赏'), ('OTHER', '其他')], max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('timezone_name', models.CharField(max_length=64)),
                ('local_date', models.DateField()),
                ('local_start_time', models.TimeField(blank=True, null=True)),
                ('boost_start_at', models.DateTimeField(blank=True, null=True)),
                ('boost_end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('racing_region', 'local_date', 'local_start_time', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('crawl', '抓取'), ('publish', '发布'), ('qq_push', 'QQ 推送')], max_length=16)),
                ('mode', models.CharField(choices=[('daily', '日常'), ('major_race', '重要赛事')], default='daily', max_length=16)),
                ('racing_region', models.CharField(blank=True, choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], max_length=32)),
                ('scope_key', models.CharField(max_length=255)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '运行中'), ('succeeded', '成功'), ('partial', '部分完成'), ('failed', '失败'), ('skipped', '跳过')], default='pending', max_length=16)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('reason_summary', models.TextField(blank=True)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('rerun_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-window_start', 'kind', 'scope_key'),
            },
        ),
        migrations.CreateModel(
            name='QuotaLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('web_publish', '网页发布'), ('qq_push', 'QQ 推送')], max_length=16)),
                ('scope', models.CharField(choices=[('region_window', '地区窗口'), ('region_hour', '地区小时'), ('group_hour', '群小时'), ('site_hour', '全站小时')], max_length=32)),
                ('scope_key', models.CharField(max_length=255)),
                ('window_start', models.DateTimeField()),
                ('limit', models.PositiveSmallIntegerField()),
                ('used', models.PositiveSmallIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-window_start', 'kind', 'scope', 'scope_key'),
            },
        ),
        migrations.CreateModel(
            name='WindowCandidateDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('selected', '入选'), ('skipped', '跳过'), ('blocked', '阻断'), ('failed', '失败')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=128)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('window', 'rank', '-score', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WindowTargetDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_key', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('selected', '入选'), ('skipped', '跳过'), ('blocked', '阻断'), ('failed', '失败')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('window', 'target', 'article_id'),
            },
        ),
        migrations.AddField(
            model_name='newssource',
            name='allow_event_boost',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='backoff_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='effective_crawl_interval_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='failure_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newssource',
            name='last_error_category',
            field=models.CharField(blank=True, choices=[('http_403', 'HTTP 403'), ('http_429', 'HTTP 429'), ('captcha_or_blocked', '验证码或疑似封禁'), ('timeout', '超时'), ('parse_error', '解析失败'), ('empty_success', '成功但无内容'), ('server_error', '服务端错误'), ('unknown', '未知')], max_length=32),
        ),
        migrations.AddField(
            model_name='newssource',
            name='manual_pause_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='production_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newssource',
            name='success_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='newssource',
            index=models.Index(fields=['enabled', 'production_approved', 'racing_region'], name='source_prod_region_idx'),
        ),
        migrations.AddIndex(
            model_name='newssource',
            index=models.Index(fields=['backoff_until'], name='source_backoff_idx'),
        ),
        migrations.AddIndex(
            model_name='majorraceevent',
            index=models.Index(fields=['racing_region', 'is_active', 'local_date'], name='major_region_date_idx'),
        ),
        migrations.AddIndex(
            model_name='majorraceevent',
            index=models.Index(fields=['boost_start_at', 'boost_end_at'], name='major_boost_window_idx'),
        ),
        migrations.AddConstraint(
            model_name='majorraceevent',
            constraint=models.UniqueConstraint(fields=('normalized_name', 'year', 'racing_region', 'race_grade'), name='uq_major_race_identity'),
        ),
        migrations.AddField(
            model_name='productionwindow',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_windows', to='stable.newssource'),
        ),
        migrations.AddField(
            model_name='productionwindow',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_windows', to='stable.pushtarget'),
        ),
        migrations.AddField(
            model_name='productionwindow',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_production_windows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='quotaledger',
            index=models.Index(fields=['kind', 'scope', 'window_start'], name='quota_kind_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='quotaledger',
            index=models.Index(fields=['scope_key', 'window_start'], name='quota_scope_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotaledger',
            constraint=models.UniqueConstraint(fields=('kind', 'scope', 'scope_key', 'window_start'), name='uq_quota_ledger_scope'),
        ),
        migrations.AddField(
            model_name='windowcandidatedecision',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_candidate_decisions', to='stable.newsarticle'),
        ),
        migrations.AddField(
            model_name='windowcandidatedecision',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_decisions', to='stable.productionwindow'),
        ),
        migrations.AddField(
            model_name='windowtargetdecision',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='window_target_decisions', to='stable.newsarticle'),
        ),
        migrations.AddField(
            model_name='windowtargetdecision',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_target_decisions', to='stable.pushtarget'),
        ),
        migrations.AddField(
            model_name='windowtargetdecision',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_decisions', to='stable.productionwindow'),
        ),
        migrations.AddIndex(
            model_name='productionwindow',
            index=models.Index(fields=['kind', 'status', 'window_start'], name='prodwin_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productionwindow',
            index=models.Index(fields=['racing_region', 'window_start'], name='prodwin_region_idx'),
        ),
        migrations.AddIndex(
            model_name='productionwindow',
            index=models.Index(fields=['lease_expires_at'], name='prodwin_lease_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionwindow',
            constraint=models.UniqueConstraint(fields=('kind', 'scope_key', 'window_start'), name='uq_prod_window_scope'),
        ),
        migrations.AddIndex(
            model_name='windowcandidatedecision',
            index=models.Index(fields=['window', 'status'], name='cand_window_status_idx'),
        ),
        migrations.AddIndex(
            model_name='windowcandidatedecision',
            index=models.Index(fields=['article', 'status'], name='cand_article_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='windowcandidatedecision',
            constraint=models.UniqueConstraint(fields=('window', 'article'), name='uq_window_candidate'),
        ),
        migrations.AddIndex(
            model_name='windowtargetdecision',
            index=models.Index(fields=['window', 'status'], name='target_window_status_idx'),
        ),
        migrations.AddIndex(
            model_name='windowtargetdecision',
            index=models.Index(fields=['target', 'status'], name='target_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='windowtargetdecision',
            constraint=models.UniqueConstraint(fields=('window', 'decision_key'), name='uq_window_target_key'),
        ),
    ]
