# Generated by Django 5.2.1 on 2026-07-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0017_majorraceevent_productionwindow_quotaledger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('crawl_failed', '来源抓取失败'), ('translation_failed', '翻译失败'), ('rewrite_failed', '改写失败'), ('publish_failed', '自动发布失败'), ('stale_source', '来源长时间无新稿'), ('backlog', '候选稿异常堆积'), ('no_auto_publish_24h', '24 小时无自动发布'), ('important_manual', '重点新闻转人工'), ('high_value_warning', '高价值新闻 warning'), ('repeated_failure', '关键任务连续失败'), ('ops_summary', '运营摘要'), ('ops_anomaly', '运营异常')], max_length=32),
        ),
    ]
