# Generated by Codex on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0018_alter_notificationlog_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="ranked_revived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
