# Generated by Django 5.2.1 on 2026-07-03 19:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0019_newsarticle_ranked_revived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=160)),
                ('series_key', models.SlugField(blank=True, max_length=160)),
                ('original_name', models.CharField(max_length=255)),
                ('chinese_name', models.CharField(max_length=255)),
                ('country_region', models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], max_length=32)),
                ('racecourse', models.CharField(max_length=255)),
                ('grade_text', models.CharField(max_length=128)),
                ('normalized_grade', models.CharField(blank=True, choices=[('G1', 'G1 / GI / GⅠ'), ('G2', 'G2 / GII / GⅡ'), ('G3', 'G3 / GIII / GⅢ'), ('JPN1', 'Jpn1 / JpnⅠ'), ('JPN2', 'Jpn2 / JpnⅡ'), ('JPN3', 'Jpn3 / JpnⅢ'), ('JG1', 'J-G1 / J・GⅠ'), ('JG2', 'J-G2 / J・GⅡ'), ('JG3', 'J-G3 / J・GⅢ'), ('L', 'Listed / リステッド'), ('OP', 'Open / オープン'), ('3WIN', '3胜级'), ('2WIN', '2胜级'), ('1WIN', '1胜级'), ('NEWCOMER', '新马'), ('MAIDEN', '未胜利'), ('LOCAL_GRADE', '地方重赏'), ('OTHER', '其他')], max_length=32)),
                ('surface', models.CharField(choices=[('turf', '草地'), ('dirt', '泥地'), ('jumps', '障碍')], max_length=16)),
                ('distance_text', models.CharField(blank=True, max_length=128)),
                ('eligibility_text', models.CharField(blank=True, max_length=255)),
                ('race_datetime', models.DateTimeField(blank=True, null=True)),
                ('timezone_name', models.CharField(default='Asia/Tokyo', max_length=64)),
                ('local_date', models.DateField(blank=True, null=True)),
                ('local_start_time', models.TimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2')], default='P2', max_length=2)),
                ('status', models.CharField(choices=[('scheduled', '赛前'), ('running', '进行中'), ('finished', '已结束'), ('postponed', '延期'), ('cancelled', '取消')], default='scheduled', max_length=16)),
                ('visibility_status', models.CharField(choices=[('draft', '草稿'), ('published', '展示'), ('hidden', '隐藏')], default='draft', max_length=16)),
                ('data_quality_status', models.CharField(choices=[('incomplete', '不完整'), ('partial', '部分完整'), ('complete', '完整')], default='incomplete', max_length=16)),
                ('is_featured', models.BooleanField(default=False)),
                ('result_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('source_refs', models.JSONField(blank=True, default=dict)),
                ('manual_lock_flags', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('external_race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_events', to='stable.externalrace')),
                ('major_race_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_events', to='stable.majorraceevent')),
            ],
            options={
                'ordering': ('local_date', 'local_start_time', 'country_region', 'chinese_name'),
            },
        ),
        migrations.CreateModel(
            name='ArticleRaceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_type', models.CharField(choices=[('pre_race', '赛前新闻'), ('post_race', '赛后新闻'), ('related', '相关新闻')], default='related', max_length=16)),
                ('status', models.CharField(choices=[('auto', '自动展示'), ('candidate', '候选'), ('manual', '人工确认'), ('removed', '人工移除')], default='candidate', max_length=16)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('matched_text', models.CharField(blank=True, max_length=255)),
                ('match_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_links', to='stable.newsarticle')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_race_article_links', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_race_article_links', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_links', to='stable.raceevent')),
            ],
            options={
                'ordering': ('event', '-confidence', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RaceEventAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('source_language', models.CharField(blank=True, choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], max_length=8)),
                ('alias_type', models.CharField(default='alias', max_length=32)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='stable.raceevent')),
            ],
            options={
                'ordering': ('event', 'source_language', 'alias_type', 'text'),
            },
        ),
        migrations.CreateModel(
            name='RaceEventDataCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('basic', '基础资料'), ('history_winners', '历史冠军'), ('runners', '出马表/闸位'), ('results', '赛果'), ('news_links', '相关新闻'), ('dynamic_fields', '动态字段')], max_length=32)),
                ('source_name', models.CharField(max_length=128)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', '待确认'), ('applied', '已应用'), ('ignored', '已忽略'), ('failed', '失败')], default='pending', max_length=16)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('candidate_payload', models.JSONField(blank=True, default=dict)),
                ('diff_payload', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_race_event_candidates', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_candidates', to='stable.raceevent')),
            ],
            options={
                'ordering': ('-fetched_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RaceEventHistoryWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('winner_year', models.PositiveSmallIntegerField()),
                ('horse_name', models.CharField(max_length=255)),
                ('jockey_name', models.CharField(blank=True, max_length=255)),
                ('trainer_name', models.CharField(blank=True, max_length=255)),
                ('finish_time', models.CharField(blank=True, max_length=64)),
                ('margin', models.CharField(blank=True, max_length=64)),
                ('source_refs', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_winners', to='stable.raceevent')),
            ],
            options={
                'ordering': ('event', '-winner_year'),
            },
        ),
        migrations.CreateModel(
            name='RaceEventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finish_position', models.PositiveSmallIntegerField()),
                ('horse_number', models.CharField(blank=True, max_length=32)),
                ('horse_name', models.CharField(max_length=255)),
                ('jockey_name', models.CharField(blank=True, max_length=255)),
                ('trainer_name', models.CharField(blank=True, max_length=255)),
                ('finish_time', models.CharField(blank=True, max_length=64)),
                ('margin', models.CharField(blank=True, max_length=64)),
                ('odds_value', models.CharField(blank=True, max_length=64)),
                ('popularity', models.CharField(blank=True, max_length=64)),
                ('barrier', models.CharField(blank=True, max_length=32)),
                ('carried_weight', models.CharField(blank=True, max_length=64)),
                ('running_status', models.CharField(blank=True, choices=[('declared', '已出走登记'), ('running', '进行中'), ('scratched', '退赛'), ('withdrawn', '取消出走'), ('unknown', '未知')], max_length=16)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('source_refs', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='stable.raceevent')),
            ],
            options={
                'ordering': ('event', 'finish_position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RaceEventRunner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('horse_number', models.CharField(blank=True, max_length=32)),
                ('barrier', models.CharField(blank=True, max_length=32)),
                ('horse_name', models.CharField(max_length=255)),
                ('jockey_name', models.CharField(blank=True, max_length=255)),
                ('trainer_name', models.CharField(blank=True, max_length=255)),
                ('carried_weight', models.CharField(blank=True, max_length=64)),
                ('odds_value', models.CharField(blank=True, max_length=64)),
                ('popularity', models.CharField(blank=True, max_length=64)),
                ('running_status', models.CharField(choices=[('declared', '已出走登记'), ('running', '进行中'), ('scratched', '退赛'), ('withdrawn', '取消出走'), ('unknown', '未知')], default='declared', max_length=16)),
                ('dynamic_updated_at', models.DateTimeField(blank=True, null=True)),
                ('manual_lock_flags', models.JSONField(blank=True, default=dict)),
                ('source_refs', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runners', to='stable.raceevent')),
            ],
            options={
                'ordering': ('event', 'sort_order', 'horse_number', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='raceevent',
            index=models.Index(fields=['visibility_status', 'local_date'], name='race_event_visible_date_idx'),
        ),
        migrations.AddIndex(
            model_name='raceevent',
            index=models.Index(fields=['country_region', 'local_date'], name='race_event_region_date_idx'),
        ),
        migrations.AddIndex(
            model_name='raceevent',
            index=models.Index(fields=['priority', 'visibility_status'], name='race_event_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='raceevent',
            index=models.Index(fields=['status', 'visibility_status'], name='race_event_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='raceevent',
            constraint=models.UniqueConstraint(fields=('year', 'slug'), name='uq_race_event_year_slug'),
        ),
        migrations.AddIndex(
            model_name='articleracelink',
            index=models.Index(fields=['event', 'status', 'link_type'], name='race_link_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='articleracelink',
            index=models.Index(fields=['article', 'status'], name='race_link_article_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='articleracelink',
            constraint=models.UniqueConstraint(fields=('event', 'article'), name='uq_article_race_link'),
        ),
        migrations.AddIndex(
            model_name='raceeventalias',
            index=models.Index(fields=['source_language', 'text'], name='race_alias_lang_text_idx'),
        ),
        migrations.AddConstraint(
            model_name='raceeventalias',
            constraint=models.UniqueConstraint(fields=('event', 'source_language', 'text'), name='uq_race_alias_event_lang_text'),
        ),
        migrations.AddIndex(
            model_name='raceeventdatacandidate',
            index=models.Index(fields=['event', 'module', 'status'], name='race_candidate_module_idx'),
        ),
        migrations.AddIndex(
            model_name='raceeventdatacandidate',
            index=models.Index(fields=['source_name', 'fetched_at'], name='race_candidate_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='raceeventhistorywinner',
            constraint=models.UniqueConstraint(fields=('event', 'winner_year'), name='uq_race_history_event_year'),
        ),
        migrations.AddConstraint(
            model_name='raceeventresult',
            constraint=models.UniqueConstraint(fields=('event', 'finish_position'), name='uq_race_result_event_pos'),
        ),
        migrations.AddIndex(
            model_name='raceeventrunner',
            index=models.Index(fields=['event', 'running_status'], name='race_runner_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='raceeventrunner',
            constraint=models.UniqueConstraint(condition=models.Q(('horse_number', ''), _negated=True), fields=('event', 'horse_number'), name='uq_race_runner_event_no'),
        ),
    ]
