# Generated by Django 5.2.1 on 2026-07-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0020_raceevent_articleracelink_raceeventalias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceevent',
            name='surface',
            field=models.CharField(choices=[('turf', '草地'), ('dirt', '泥地'), ('synthetic', '复合赛道'), ('jumps', '障碍')], max_length=16),
        ),
    ]
