# Generated by Django 5.2.1 on 2026-07-07 14:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0021_alter_raceevent_surface'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name_zh', models.CharField(blank=True, max_length=255)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('english_name', models.CharField(blank=True, max_length=255)),
                ('japanese_name', models.CharField(blank=True, max_length=255)),
                ('racing_region', models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], default='japan', max_length=32)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('sex', models.CharField(blank=True, max_length=64)),
                ('color', models.CharField(blank=True, max_length=128)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('trainer_name', models.CharField(blank=True, max_length=255)),
                ('breeder_name', models.CharField(blank=True, max_length=255)),
                ('intro', models.TextField(blank=True)),
                ('sire_text', models.CharField(blank=True, max_length=255)),
                ('dam_text', models.CharField(blank=True, max_length=255)),
                ('sire_sire_text', models.CharField(blank=True, max_length=255)),
                ('sire_dam_text', models.CharField(blank=True, max_length=255)),
                ('dam_sire_text', models.CharField(blank=True, max_length=255)),
                ('dam_dam_text', models.CharField(blank=True, max_length=255)),
                ('review_status', models.CharField(choices=[('draft', '草稿'), ('ready', '待发布'), ('published', '展示'), ('hidden', '隐藏')], default='draft', max_length=16)),
                ('completeness_status', models.CharField(choices=[('empty', '空壳'), ('profile_only', '仅基础资料'), ('partial_pedigree', '部分血统'), ('complete_pedigree_2gen', '完整二代血统')], default='empty', max_length=32)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('manual_lock_flags', models.JSONField(blank=True, default=dict)),
                ('source_refs', models.JSONField(blank=True, default=dict)),
                ('dam_dam_horse_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.horseprofile')),
                ('dam_dam_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.termentry')),
                ('dam_horse_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_children', to='stable.horseprofile')),
                ('dam_sire_horse_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.horseprofile')),
                ('dam_sire_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.termentry')),
                ('dam_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.termentry')),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_horse_profiles', to=settings.AUTH_USER_MODEL)),
                ('primary_term', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='horse_profile', to='stable.termentry')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_horse_profiles', to=settings.AUTH_USER_MODEL)),
                ('sire_dam_horse_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.horseprofile')),
                ('sire_dam_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.termentry')),
                ('sire_horse_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sire_children', to='stable.horseprofile')),
                ('sire_sire_horse_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.horseprofile')),
                ('sire_sire_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.termentry')),
                ('sire_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.termentry')),
            ],
            options={
                'ordering': ('racing_region', 'display_name_zh', 'original_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HorseFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('include_descendants', models.BooleanField(default=True)),
                ('descendant_depth', models.PositiveSmallIntegerField(default=2)),
                ('followed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horse_follows', to=settings.AUTH_USER_MODEL)),
                ('horse_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='stable.horseprofile')),
            ],
            options={
                'ordering': ('-followed_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ArticleHorseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('auto', '自动展示'), ('candidate', '候选'), ('manual', '人工确认'), ('removed', '人工移除')], default='candidate', max_length=16)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('matched_text', models.CharField(blank=True, max_length=255)),
                ('match_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horse_links', to='stable.newsarticle')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_horse_article_links', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_horse_article_links', to=settings.AUTH_USER_MODEL)),
                ('horse_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_links', to='stable.horseprofile')),
            ],
            options={
                'ordering': ('horse_profile', '-confidence', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='HorseProfileDataCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('profile', '基础资料'), ('pedigree', '血统'), ('race_record', '参赛履历'), ('aliases', '别名')], max_length=32)),
                ('source_name', models.CharField(max_length=128)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', '待确认'), ('applied', '已应用'), ('ignored', '已忽略'), ('conflict', '冲突'), ('failed', '失败')], default='pending', max_length=16)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('candidate_payload', models.JSONField(blank=True, default=dict)),
                ('diff_payload', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('result_summary', models.TextField(blank=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_horse_profile_candidates', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_candidates', to='stable.horseprofile')),
            ],
            options={
                'ordering': ('-fetched_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='HorseRaceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_type', models.CharField(choices=[('major_win', '主胜鞍赛事'), ('related', '相关赛事'), ('manual', '人工相关')], default='related', max_length=16)),
                ('status', models.CharField(choices=[('auto', '自动展示'), ('candidate', '候选'), ('manual', '人工确认'), ('removed', '人工移除')], default='candidate', max_length=16)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_horse_race_links', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horse_links', to='stable.raceevent')),
                ('horse_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_links', to='stable.horseprofile')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_horse_race_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('horse_profile', 'link_type', '-confidence', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='HorseRaceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race_name', models.CharField(max_length=255)),
                ('race_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('race_date', models.DateField(blank=True, null=True)),
                ('grade_text', models.CharField(blank=True, max_length=128)),
                ('normalized_grade', models.CharField(blank=True, choices=[('G1', 'G1 / GI / GⅠ'), ('G2', 'G2 / GII / GⅡ'), ('G3', 'G3 / GIII / GⅢ'), ('JPN1', 'Jpn1 / JpnⅠ'), ('JPN2', 'Jpn2 / JpnⅡ'), ('JPN3', 'Jpn3 / JpnⅢ'), ('JG1', 'J-G1 / J・GⅠ'), ('JG2', 'J-G2 / J・GⅡ'), ('JG3', 'J-G3 / J・GⅢ'), ('L', 'Listed / リステッド'), ('OP', 'Open / オープン'), ('3WIN', '3胜级'), ('2WIN', '2胜级'), ('1WIN', '1胜级'), ('NEWCOMER', '新马'), ('MAIDEN', '未胜利'), ('LOCAL_GRADE', '地方重赏'), ('OTHER', '其他')], max_length=32)),
                ('racecourse', models.CharField(blank=True, max_length=255)),
                ('distance_text', models.CharField(blank=True, max_length=128)),
                ('surface', models.CharField(blank=True, choices=[('turf', '草地'), ('dirt', '泥地'), ('synthetic', '复合赛道'), ('jumps', '障碍')], max_length=16)),
                ('finish_position', models.CharField(blank=True, max_length=32)),
                ('result_status', models.CharField(choices=[('won', '胜出'), ('placed', '上名'), ('unplaced', '未上名'), ('scratched', '退赛'), ('unknown', '未知')], default='unknown', max_length=16)),
                ('is_major_win', models.BooleanField(default=False)),
                ('major_win_order', models.PositiveSmallIntegerField(default=0)),
                ('source_name', models.CharField(blank=True, max_length=128)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_refs', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horse_records', to='stable.raceevent')),
                ('horse_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_records', to='stable.horseprofile')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horse_records', to='stable.raceeventresult')),
            ],
            options={
                'ordering': ('horse_profile', '-race_date', '-race_year', 'major_win_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='horseprofile',
            index=models.Index(fields=['review_status', 'racing_region'], name='horse_status_region_idx'),
        ),
        migrations.AddIndex(
            model_name='horseprofile',
            index=models.Index(fields=['racing_region', 'display_name_zh'], name='horse_region_name_idx'),
        ),
        migrations.AddIndex(
            model_name='horseprofile',
            index=models.Index(fields=['completeness_status', 'review_status'], name='horse_complete_status_idx'),
        ),
        migrations.AddIndex(
            model_name='horseprofile',
            index=models.Index(fields=['is_featured', 'review_status'], name='horse_featured_status_idx'),
        ),
        migrations.AddIndex(
            model_name='horsefollow',
            index=models.Index(fields=['horse_profile', 'include_descendants'], name='horse_follow_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='horsefollow',
            index=models.Index(fields=['user', 'horse_profile'], name='horse_follow_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='horsefollow',
            constraint=models.UniqueConstraint(fields=('token_hash', 'horse_profile'), name='uq_horse_follow_token_profile'),
        ),
        migrations.AddIndex(
            model_name='articlehorselink',
            index=models.Index(fields=['horse_profile', 'status'], name='horse_link_status_idx'),
        ),
        migrations.AddIndex(
            model_name='articlehorselink',
            index=models.Index(fields=['article', 'status'], name='horse_link_article_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='articlehorselink',
            constraint=models.UniqueConstraint(fields=('horse_profile', 'article'), name='uq_article_horse_link'),
        ),
        migrations.AddIndex(
            model_name='horseprofiledatacandidate',
            index=models.Index(fields=['profile', 'module', 'status'], name='horse_candidate_module_idx'),
        ),
        migrations.AddIndex(
            model_name='horseprofiledatacandidate',
            index=models.Index(fields=['source_name', 'fetched_at'], name='horse_candidate_source_idx'),
        ),
        migrations.AddIndex(
            model_name='horseracelink',
            index=models.Index(fields=['horse_profile', 'status', 'link_type'], name='horse_race_link_status_idx'),
        ),
        migrations.AddIndex(
            model_name='horseracelink',
            index=models.Index(fields=['event', 'status'], name='horse_race_link_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='horseracelink',
            constraint=models.UniqueConstraint(fields=('horse_profile', 'event', 'link_type'), name='uq_horse_race_link'),
        ),
        migrations.AddIndex(
            model_name='horseracerecord',
            index=models.Index(fields=['horse_profile', 'result_status'], name='horse_record_result_idx'),
        ),
        migrations.AddIndex(
            model_name='horseracerecord',
            index=models.Index(fields=['horse_profile', 'is_major_win'], name='horse_record_major_idx'),
        ),
        migrations.AddIndex(
            model_name='horseracerecord',
            index=models.Index(fields=['event', 'result_status'], name='horse_record_event_idx'),
        ),
    ]
