# Generated by Django 5.2.1 on 2026-07-10 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0022_horseprofile_horsefollow_articlehorselink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='attribution_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='attribution_source',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='attribution_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content_category',
            field=models.CharField(blank=True, choices=[('news', '新闻'), ('preview', '赛前展望'), ('result_brief', '赛果简报'), ('official_notice', '官方通知'), ('racecard_update', '出赛/排位更新'), ('tips', '赛前预测/投注倾向'), ('feature', '特写'), ('sales_breeding', '育马/拍卖/机构'), ('flash', '快讯（旧）'), ('pre_race', '赛前前瞻（旧）'), ('post_race', '赛后结果/复盘（旧）'), ('official', '官方公告（旧）'), ('interview', '采访/人物（旧）'), ('other', '其他')], default='news', max_length=32),
        ),
        migrations.CreateModel(
            name='NewsArticleRelatedRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], max_length=32)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('is_manual', models.BooleanField(default=False)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_region_links', to='stable.newsarticle')),
            ],
            options={
                'ordering': ('region', 'id'),
                'indexes': [models.Index(fields=['region', 'article'], name='related_region_article_idx'), models.Index(fields=['article', 'region'], name='article_related_region_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'region'), name='uq_article_related_region')],
            },
        ),
    ]
