# Generated by Django 5.2.1 on 2026-07-11 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_official_finish_positions(apps, schema_editor):
    race_event_result = apps.get_model('stable', 'RaceEventResult')
    pending = []
    for result in race_event_result.objects.only(
        'id',
        'finish_position',
        'official_finish_position',
        'source_refs',
    ).iterator(chunk_size=1000):
        source_refs = result.source_refs if isinstance(result.source_refs, dict) else {}
        source_value = source_refs.get('official_finish_position')
        try:
            official_position = int(source_value)
        except (TypeError, ValueError):
            official_position = result.finish_position
        if isinstance(source_value, bool) or official_position <= 0 or official_position > 32767:
            official_position = result.finish_position
        result.official_finish_position = official_position
        pending.append(result)
        if len(pending) == 1000:
            race_event_result.objects.bulk_update(pending, ['official_finish_position'], batch_size=1000)
            pending.clear()
    if pending:
        race_event_result.objects.bulk_update(pending, ['official_finish_position'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0023_multiregion_news_attribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRaceEventTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('country_region', models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], max_length=32)),
                ('expectation_status', models.CharField(choices=[('held', '应举办'), ('cancelled', '已取消'), ('not_due', '尚未到期'), ('not_held', '该年未举办')], default='held', max_length=16)),
                ('resolution_status', models.CharField(choices=[('pending', '待处理'), ('ready', '可导入'), ('source_unavailable', '来源暂不可得'), ('identity_review_required', '系列身份待审'), ('permanently_unavailable', '永久不可得'), ('imported', '已导入')], default='pending', max_length=32)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('chinese_name', models.CharField(blank=True, max_length=255)),
                ('grade_text', models.CharField(blank=True, max_length=128)),
                ('normalized_grade', models.CharField(blank=True, choices=[('G1', 'G1 / GI / GⅠ'), ('G2', 'G2 / GII / GⅡ'), ('G3', 'G3 / GIII / GⅢ'), ('JPN1', 'Jpn1 / JpnⅠ'), ('JPN2', 'Jpn2 / JpnⅡ'), ('JPN3', 'Jpn3 / JpnⅢ'), ('JG1', 'J-G1 / J・GⅠ'), ('JG2', 'J-G2 / J・GⅡ'), ('JG3', 'J-G3 / J・GⅢ'), ('L', 'Listed / リステッド'), ('OP', 'Open / オープン'), ('3WIN', '3胜级'), ('2WIN', '2胜级'), ('1WIN', '1胜级'), ('NEWCOMER', '新马'), ('MAIDEN', '未胜利'), ('LOCAL_GRADE', '地方重赏'), ('OTHER', '其他')], max_length=32)),
                ('racecourse', models.CharField(blank=True, max_length=255)),
                ('surface', models.CharField(blank=True, choices=[('turf', '草地'), ('dirt', '泥地'), ('synthetic', '复合赛道'), ('jumps', '障碍')], max_length=16)),
                ('distance_text', models.CharField(blank=True, max_length=128)),
                ('local_date', models.DateField(blank=True, null=True)),
                ('module_statuses', models.JSONField(blank=True, default=dict)),
                ('field_provenance', models.JSONField(blank=True, default=dict)),
                ('source_refs', models.JSONField(blank=True, default=dict)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('permanent_unavailable_approved_at', models.DateTimeField(blank=True, null=True)),
                ('permanent_unavailable_evidence', models.JSONField(blank=True, default=dict)),
                ('last_run_id', models.CharField(blank=True, max_length=64)),
                ('artifact_sha256', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('country_region', 'year', 'race_series'),
            },
        ),
        migrations.CreateModel(
            name='RaceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=160, unique=True)),
                ('country_region', models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('other', '其他')], max_length=32)),
                ('canonical_name_original', models.CharField(max_length=255)),
                ('chinese_name', models.CharField(blank=True, max_length=255)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ended_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '现行'), ('discontinued', '已停办'), ('unknown', '待确认')], default='unknown', max_length=16)),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已驳回')], default='pending', max_length=16)),
                ('source_refs', models.JSONField(blank=True, default=dict)),
                ('manual_lock_flags', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('country_region', 'canonical_name_original', 'key'),
            },
        ),
        migrations.CreateModel(
            name='RaceSeriesName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('normalized_text', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source_language', models.CharField(blank=True, choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], max_length=8)),
                ('name_type', models.CharField(choices=[('canonical', '正式名称'), ('historical', '历史名称'), ('sponsored', '冠名名称'), ('alias', '别名')], default='alias', max_length=16)),
                ('valid_from_year', models.PositiveSmallIntegerField(default=0)),
                ('valid_to_year', models.PositiveSmallIntegerField(default=0)),
                ('source_refs', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('series', 'valid_from_year', 'name_type', 'text'),
            },
        ),
        migrations.CreateModel(
            name='RaceSeriesRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('predecessor', '前身'), ('successor', '后继'), ('merged_into', '并入'), ('split_into', '拆分为'), ('replaced_by', '被替代')], max_length=16)),
                ('effective_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_refs', models.JSONField(blank=True, default=dict)),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已驳回')], default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('from_series', 'effective_year', 'relation_type', 'to_series'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='raceeventhistorywinner',
            name='uq_race_history_event_year',
        ),
        migrations.AddField(
            model_name='raceeventresult',
            name='official_finish_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_official_finish_positions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='raceeventhistorywinner',
            constraint=models.UniqueConstraint(fields=('event', 'winner_year', 'horse_name'), name='uq_race_history_event_year_horse'),
        ),
        migrations.AddField(
            model_name='historicalraceeventtarget',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_target', to='stable.raceevent'),
        ),
        migrations.AddField(
            model_name='historicalraceeventtarget',
            name='permanent_unavailable_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_permanent_race_gaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='raceseries',
            index=models.Index(fields=['country_region', 'status'], name='race_series_region_status_idx'),
        ),
        migrations.AddIndex(
            model_name='raceseries',
            index=models.Index(fields=['review_status', 'country_region'], name='race_series_review_region_idx'),
        ),
        migrations.AddConstraint(
            model_name='raceseries',
            constraint=models.CheckConstraint(condition=models.Q(('founded_year__isnull', True), ('ended_year__isnull', True), ('founded_year__lte', models.F('ended_year')), _connector='OR'), name='race_series_valid_years'),
        ),
        migrations.AddField(
            model_name='historicalraceeventtarget',
            name='race_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_targets', to='stable.raceseries'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='race_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annual_events', to='stable.raceseries'),
        ),
        migrations.AddConstraint(
            model_name='raceevent',
            constraint=models.UniqueConstraint(condition=models.Q(('race_series__isnull', False)), fields=('race_series', 'year'), name='uq_race_event_series_year'),
        ),
        migrations.AddField(
            model_name='raceseriesname',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='stable.raceseries'),
        ),
        migrations.AddField(
            model_name='raceseriesrelation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_race_series_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='raceseriesrelation',
            name='from_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='stable.raceseries'),
        ),
        migrations.AddField(
            model_name='raceseriesrelation',
            name='to_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='stable.raceseries'),
        ),
        migrations.AddIndex(
            model_name='historicalraceeventtarget',
            index=models.Index(fields=['country_region', 'year', 'expectation_status', 'resolution_status'], name='hist_target_region_year_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalraceeventtarget',
            index=models.Index(fields=['resolution_status', 'last_checked_at'], name='hist_target_resolution_idx'),
        ),
        migrations.AddConstraint(
            model_name='historicalraceeventtarget',
            constraint=models.UniqueConstraint(fields=('race_series', 'year'), name='uq_historical_target_series_year'),
        ),
        migrations.AddConstraint(
            model_name='historicalraceeventtarget',
            constraint=models.CheckConstraint(condition=models.Q(('event__isnull', False), ('expectation_status', 'not_held'), _negated=True), name='hist_target_not_held_no_event'),
        ),
        migrations.AddConstraint(
            model_name='historicalraceeventtarget',
            constraint=models.CheckConstraint(condition=models.Q(('expectation_status', 'not_due'), ('resolution_status', 'imported'), _negated=True), name='hist_target_not_due_unimported'),
        ),
        migrations.AddConstraint(
            model_name='raceseriesname',
            constraint=models.UniqueConstraint(fields=('series', 'source_language', 'normalized_text', 'valid_from_year'), name='uq_series_name_lang_text_from'),
        ),
        migrations.AddConstraint(
            model_name='raceseriesname',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from_year', 0), ('valid_to_year', 0), ('valid_from_year__lte', models.F('valid_to_year')), _connector='OR'), name='series_name_valid_years'),
        ),
        migrations.AddConstraint(
            model_name='raceseriesrelation',
            constraint=models.UniqueConstraint(fields=('from_series', 'to_series', 'relation_type'), name='uq_series_relation_direction_type'),
        ),
        migrations.AddConstraint(
            model_name='raceseriesrelation',
            constraint=models.CheckConstraint(condition=models.Q(('from_series', models.F('to_series')), _negated=True), name='series_relation_no_self'),
        ),
    ]
