# Generated by Django 5.2.1 on 2026-07-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0024_historical_race_inventory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='raceevent',
            index=models.Index(fields=['visibility_status', 'year'], name='race_event_visible_year_idx'),
        ),
        migrations.AddIndex(
            model_name='raceevent',
            index=models.Index(fields=['visibility_status', 'data_quality_status', 'year', 'slug'], name='race_event_sitemap_idx'),
        ),
        migrations.AddIndex(
            model_name='raceeventresult',
            index=models.Index(fields=['official_finish_position', 'event'], name='race_result_official_event_idx'),
        ),
    ]
