# Generated by Codex on 2026-07-10

import hashlib

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def initialize_term_translation_status(apps, schema_editor):
    TermEntry = apps.get_model("stable", "TermEntry")
    TermEntry.objects.filter(term_type="horse", target_zh="").update(translation_status="pending")
    TermEntry.objects.exclude(target_zh="").update(translation_status="translated")


def backfill_horse_record_idempotency_keys(apps, schema_editor):
    HorseRaceRecord = apps.get_model("stable", "HorseRaceRecord")
    grouped: dict[tuple[int, str], list[int]] = {}
    for record in HorseRaceRecord.objects.filter(idempotency_key="").iterator():
        raw_payload = record.raw_payload if isinstance(record.raw_payload, dict) else {}
        source_refs = record.source_refs if isinstance(record.source_refs, dict) else {}
        effective_source_name = str(record.source_name or "").strip()
        if not effective_source_name:
            effective_source_name = next(
                (
                    str(evidence.get(key) or "").strip()
                    for evidence in (raw_payload, source_refs)
                    for key in ("source", "source_name", "provider", "adapter")
                    if str(evidence.get(key) or "").strip()
                ),
                "",
            )
            if effective_source_name:
                HorseRaceRecord.objects.filter(pk=record.pk, source_name="").update(
                    source_name=effective_source_name
                )
        external_id = next(
            (
                evidence.get(key)
                for evidence in (raw_payload, source_refs)
                for key in ("external_result_id", "external_race_id", "idempotency_key")
                if evidence.get(key)
            ),
            None,
        )
        external_id = str(external_id or "").strip()
        source_identity = effective_source_name.casefold()
        if external_id:
            raw = f"{record.horse_profile_id}|external|{source_identity}|{external_id}"
        else:
            raw = "|".join(
                [
                    str(record.horse_profile_id),
                    source_identity,
                    str(record.race_date or record.race_year or ""),
                    str(record.race_name or ""),
                    str(record.racecourse or ""),
                    str(record.source_url or ""),
                ]
            )
        key = hashlib.sha256(raw.encode("utf-8")).hexdigest()
        grouped.setdefault((record.horse_profile_id, key), []).append(record.id)
    for (_profile_id, key), record_ids in grouped.items():
        if len(record_ids) == 1:
            HorseRaceRecord.objects.filter(pk=record_ids[0], idempotency_key="").update(idempotency_key=key)


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0026_historical_race_query_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="termentry",
            name="target_zh",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="termentry",
            name="translation_status",
            field=models.CharField(
                choices=[("pending", "中文名待补"), ("translated", "已有中文名")],
                default="translated",
                max_length=16,
            ),
        ),
        migrations.RunPython(initialize_term_translation_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="horseprofile",
            name="completeness_status",
            field=models.CharField(
                choices=[
                    ("empty", "空壳"),
                    ("profile_only", "仅基础资料"),
                    ("partial_pedigree", "部分血统"),
                    ("complete_pedigree_2gen", "完整二代血统"),
                    ("complete_profile_full", "完整马匹资料"),
                ],
                default="empty",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="racing_career_status",
            field=models.CharField(
                choices=[("active", "在役"), ("retired", "退役"), ("unknown", "未知")],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="records_synced_through",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="full_profile_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="full_profile_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_full_horse_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="auto_update_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="auto_first_publish_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="horseprofiledatacandidate",
            name="module",
            field=models.CharField(
                choices=[
                    ("profile", "基础资料"),
                    ("pedigree", "血统"),
                    ("race_record", "参赛履历"),
                    ("major_wins", "主胜鞍"),
                    ("aliases", "别名"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="horseracerecord",
            name="result_status",
            field=models.CharField(
                choices=[
                    ("won", "胜出"),
                    ("placed", "上名"),
                    ("unplaced", "未上名"),
                    ("scratched", "退赛"),
                    ("withdrawn", "取消出走"),
                    ("did_not_finish", "未完赛"),
                    ("disqualified", "失格"),
                    ("unknown", "未知"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="HorseProfileCompletionRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "已计划"),
                            ("running", "运行中"),
                            ("dry_run", "Dry-run 完成"),
                            ("committed", "已写入"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("dry_run", models.BooleanField(default=True)),
                ("regions", models.JSONField(blank=True, default=list)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("artifact_path", models.CharField(blank=True, max_length=1000)),
                ("source_names", models.JSONField(blank=True, default=list)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "operated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="horse_profile_completion_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="horseprofiledatacandidate",
            name="completion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="stable.horseprofilecompletionrun",
            ),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="completion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="race_records",
                to="stable.horseprofilecompletionrun",
            ),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(backfill_horse_record_idempotency_keys, migrations.RunPython.noop),
        migrations.CreateModel(
            name="HorseP0Source",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("term_active_with_zh", "有中文名 active 术语"),
                            ("major_race_participant", "重点赛事参赛马"),
                            ("manual", "人工标记"),
                        ],
                        max_length=32,
                    ),
                ),
                ("status", models.CharField(choices=[("active", "有效"), ("revoked", "已撤销")], default="active", max_length=16)),
                (
                    "racing_region",
                    models.CharField(
                        choices=[
                            ("japan", "日本"),
                            ("hong_kong", "中国香港"),
                            ("united_kingdom", "英国"),
                            ("france", "法国"),
                            ("united_states", "美国"),
                            ("other", "其他"),
                        ],
                        default="japan",
                        max_length=32,
                    ),
                ),
                (
                    "race_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("G1", "G1 / GI / GⅠ"),
                            ("G2", "G2 / GII / GⅡ"),
                            ("G3", "G3 / GIII / GⅢ"),
                            ("JPN1", "Jpn1 / JpnⅠ"),
                            ("JPN2", "Jpn2 / JpnⅡ"),
                            ("JPN3", "Jpn3 / JpnⅢ"),
                            ("JG1", "J-G1 / J・GⅠ"),
                            ("JG2", "J-G2 / J・GⅡ"),
                            ("JG3", "J-G3 / J・GⅢ"),
                            ("L", "Listed / リステッド"),
                            ("OP", "Open / オープン"),
                            ("3WIN", "3胜级"),
                            ("2WIN", "2胜级"),
                            ("1WIN", "1胜级"),
                            ("NEWCOMER", "新马"),
                            ("MAIDEN", "未胜利"),
                            ("LOCAL_GRADE", "地方重赏"),
                            ("OTHER", "其他"),
                        ],
                        max_length=32,
                    ),
                ),
                ("horse_name", models.CharField(blank=True, max_length=255)),
                ("participant_key", models.CharField(blank=True, max_length=255)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("evidence_summary", models.TextField(blank=True)),
                ("evidence_payload", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_reason", models.TextField(blank=True)),
                (
                    "completion_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="p0_sources",
                        to="stable.horseprofilecompletionrun",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="p0_sources", to="stable.horseprofile"),
                ),
                (
                    "race_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="horse_p0_sources",
                        to="stable.raceevent",
                    ),
                ),
                (
                    "race_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="horse_p0_sources",
                        to="stable.raceeventresult",
                    ),
                ),
                (
                    "race_runner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="horse_p0_sources",
                        to="stable.raceeventrunner",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="p0_sources",
                        to="stable.termentry",
                    ),
                ),
            ],
            options={
                "ordering": ("profile", "source_type", "-observed_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="HorseIdentityConflict",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待处理"), ("resolved", "已解决"), ("ignored", "已忽略")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("horse_name", models.CharField(max_length=255)),
                ("horse_number", models.CharField(blank=True, max_length=32)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("identity_keys", models.JSONField(blank=True, default=list)),
                ("sire_name", models.CharField(blank=True, max_length=255)),
                ("dam_name", models.CharField(blank=True, max_length=255)),
                ("birth_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("evidence_payload", models.JSONField(blank=True, default=dict)),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_horse_number", models.CharField(blank=True, max_length=32)),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate_profiles",
                    models.ManyToManyField(blank=True, related_name="identity_conflicts", to="stable.horseprofile"),
                ),
                (
                    "candidate_terms",
                    models.ManyToManyField(blank=True, related_name="horse_identity_conflicts", to="stable.termentry"),
                ),
                (
                    "race_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="horse_identity_conflicts",
                        to="stable.raceevent",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_horse_identity_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_identity_conflicts",
                        to="stable.horseprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("status", "-observed_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="horseprofile",
            index=models.Index(fields=["racing_region", "records_synced_through"], name="horse_region_sync_idx"),
        ),
        migrations.AddIndex(
            model_name="horseprofilecompletionrun",
            index=models.Index(fields=["status", "created_at"], name="horse_run_status_idx"),
        ),
        migrations.AddIndex(
            model_name="horseracerecord",
            index=models.Index(fields=["horse_profile", "idempotency_key"], name="horse_record_idem_idx"),
        ),
        migrations.AddConstraint(
            model_name="horseracerecord",
            constraint=models.UniqueConstraint(
                condition=~models.Q(idempotency_key=""),
                fields=("horse_profile", "idempotency_key"),
                name="uq_horse_record_idempotency",
            ),
        ),
        migrations.AddIndex(
            model_name="horsep0source",
            index=models.Index(fields=["source_type", "status"], name="horse_p0_type_status_idx"),
        ),
        migrations.AddIndex(
            model_name="horsep0source",
            index=models.Index(fields=["racing_region", "status"], name="horse_p0_region_status_idx"),
        ),
        migrations.AddIndex(
            model_name="horsep0source",
            index=models.Index(fields=["race_event", "source_type"], name="horse_p0_event_type_idx"),
        ),
        migrations.AddIndex(
            model_name="horsep0source",
            index=models.Index(fields=["race_event", "participant_key"], name="horse_p0_participant_idx"),
        ),
        migrations.AddIndex(
            model_name="horsep0source",
            index=models.Index(fields=["completion_run", "status"], name="horse_p0_run_status_idx"),
        ),
        migrations.AddIndex(
            model_name="horseidentityconflict",
            index=models.Index(fields=["status", "observed_at"], name="horse_identity_status_idx"),
        ),
        migrations.AddIndex(
            model_name="horseidentityconflict",
            index=models.Index(fields=["race_event", "status"], name="horse_identity_event_idx"),
        ),
        migrations.AddConstraint(
            model_name="horsep0source",
            constraint=models.UniqueConstraint(
                condition=models.Q(source_type="term_active_with_zh"),
                fields=("profile", "source_type", "term"),
                name="uq_horse_p0_term_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="horsep0source",
            constraint=models.UniqueConstraint(
                condition=models.Q(source_type="manual"),
                fields=("profile", "source_type"),
                name="uq_horse_p0_manual_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="horsep0source",
            constraint=models.UniqueConstraint(
                condition=models.Q(source_type="major_race_participant", status="active"),
                fields=("source_type", "race_event", "participant_key"),
                name="uq_horse_p0_major_race_source",
            ),
        ),
    ]
