# Generated by Django 5.2.1 on 2026-07-12 18:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0028_term_gate_reprocess_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='attribution_confidence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='attribution_rule_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='attribution_status',
            field=models.CharField(blank=True, choices=[('applied', '已应用'), ('fallback', '来源兜底'), ('needs_review', '待复核'), ('locked_skip', '人工锁定跳过')], db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='published_at_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='published_at_verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='translation_error_category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='translation_next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='translation_retry_exhausted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushtarget',
            name='multiregion_test_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MultiregionAttributionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('dry_run', 'Dry run'), ('commit', 'Commit')], max_length=16)),
                ('selectors', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('partial', '部分完成'), ('failed', '失败'), ('rejected', '已拒绝')], default='pending', max_length=16)),
                ('cursor', models.PositiveIntegerField(default=0)),
                ('completed_article_ids', models.JSONField(blank=True, default=list)),
                ('rule_version', models.CharField(blank=True, max_length=64)),
                ('term_version', models.CharField(blank=True, max_length=64)),
                ('gold_version', models.CharField(blank=True, max_length=64)),
                ('settings_sha256', models.CharField(blank=True, max_length=64)),
                ('term_snapshot_sha256', models.CharField(blank=True, max_length=64)),
                ('gold_snapshot_sha256', models.CharField(blank=True, max_length=64)),
                ('candidate_fingerprint', models.CharField(blank=True, max_length=64)),
                ('candidate_payload', models.JSONField(blank=True, default=list)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('manifest_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-started_at', '-id'),
                'indexes': [models.Index(fields=['status', '-started_at'], name='attr_run_status_idx'), models.Index(fields=['mode', '-started_at'], name='attr_run_mode_idx')],
            },
        ),
        migrations.CreateModel(
            name='MultiregionAttributionLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('owner_token', models.CharField(blank=True, max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='stable.multiregionattributionrun')),
            ],
            options={
                'ordering': ('key',),
            },
        ),
    ]
