# Generated by Django 5.2.1 on 2026-07-14 05:11

import django.db.models.deletion
from django.db import migrations, models


def create_append_only_event_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION stable_reject_historical_batch_event_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'stable_historicalbatchrunevent is append-only';
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER stable_historical_batch_event_append_only
        BEFORE UPDATE OR DELETE ON stable_historicalbatchrunevent
        FOR EACH ROW EXECUTE FUNCTION stable_reject_historical_batch_event_mutation();
        """
    )
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION stable_reject_historical_runner_visibility_change()
        RETURNS trigger AS $$
        BEGIN
            IF current_setting('application_name', true) LIKE 'umanews-historical-runner:%%' THEN
                IF TG_OP = 'DELETE' THEN
                    RAISE EXCEPTION 'historical runner cannot delete RaceEvent';
                ELSIF TG_OP = 'INSERT' AND NEW.visibility_status = 'published' THEN
                    RAISE EXCEPTION 'historical runner cannot publish RaceEvent';
                ELSIF TG_OP = 'UPDATE'
                      AND NEW.visibility_status IS DISTINCT FROM OLD.visibility_status
                THEN
                    RAISE EXCEPTION 'historical runner cannot change RaceEvent visibility';
                END IF;
            END IF;
            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER stable_historical_runner_visibility_guard
        BEFORE INSERT OR UPDATE OR DELETE ON stable_raceevent
        FOR EACH ROW EXECUTE FUNCTION stable_reject_historical_runner_visibility_change();
        """
    )


def drop_append_only_event_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS stable_historical_runner_visibility_guard
        ON stable_raceevent;
        DROP FUNCTION IF EXISTS stable_reject_historical_runner_visibility_change();
        DROP TRIGGER IF EXISTS stable_historical_batch_event_append_only
        ON stable_historicalbatchrunevent;
        DROP FUNCTION IF EXISTS stable_reject_historical_batch_event_mutation();
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0030_japanese_racing_translation_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('batch_id', models.CharField(db_index=True, max_length=128)),
                ('phase', models.CharField(choices=[('crawl', '抓取'), ('apply', '落库'), ('verify', '核验')], max_length=16)),
                ('status', models.CharField(choices=[('planned', '待执行'), ('running', '运行中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '失败'), ('blocked', '已阻断')], default='planned', max_length=16)),
                ('network_enabled', models.BooleanField(default=False)),
                ('write_enabled', models.BooleanField(default=False)),
                ('image_id', models.CharField(max_length=128)),
                ('image_revision', models.CharField(max_length=64)),
                ('artifact_root', models.TextField()),
                ('plan_sha256', models.CharField(max_length=64)),
                ('owner_token_sha256', models.CharField(blank=True, max_length=64)),
                ('current_step', models.CharField(blank=True, max_length=128)),
                ('checkpoint', models.JSONField(blank=True, default=dict)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('pause_requested_at', models.DateTimeField(blank=True, null=True)),
                ('pause_requested_by', models.CharField(blank=True, max_length=128)),
                ('pause_reason', models.TextField(blank=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', '-created_at'], name='hist_batch_run_status_idx'), models.Index(fields=['batch_id', 'phase'], name='hist_batch_run_batch_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('network_enabled', True), ('write_enabled', True), _negated=True), name='hist_batch_no_network_write'), models.CheckConstraint(condition=models.Q(models.Q(('network_enabled', True), ('phase', 'crawl'), ('write_enabled', False)), models.Q(('network_enabled', False), ('phase', 'apply'), ('write_enabled', True)), models.Q(('network_enabled', False), ('phase', 'verify'), ('write_enabled', False)), _connector='OR'), name='hist_batch_phase_permissions')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBatchLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='global', max_length=64, unique=True)),
                ('owner_token_sha256', models.CharField(blank=True, max_length=64)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='stable.historicalbatchrun')),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalBatchRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=32)),
                ('phase', models.CharField(blank=True, choices=[('crawl', '抓取'), ('apply', '落库'), ('verify', '核验')], max_length=16)),
                ('step_id', models.CharField(blank=True, max_length=128)),
                ('owner_prefix', models.CharField(blank=True, max_length=16)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stable.historicalbatchrun')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['run', 'created_at'], name='hist_batch_event_run_idx'), models.Index(fields=['event_type', 'created_at'], name='hist_batch_event_type_idx')],
            },
        ),
        migrations.RunPython(
            create_append_only_event_trigger,
            drop_append_only_event_trigger,
        ),
    ]
