# Generated by Django 5.2.1 on 2026-07-15 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0031_historical_batch_runner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRaceDetailImportReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_id', models.CharField(max_length=64, unique=True)),
                ('layer', models.CharField(choices=[('historical_through_2024', '截至2024年历史赛事'), ('current_year_due', '当前年度已到期赛事')], max_length=32)),
                ('bundle_sha256', models.CharField(max_length=64)),
                ('chunk_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('started', '已开始'), ('completed', '已完成'), ('abandoned', '已废弃')], default='started', max_length=16)),
                ('target_count', models.PositiveIntegerField()),
                ('initial_payload', models.JSONField(default=dict)),
                ('completion_payload', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('abandoned_at', models.DateTimeField(blank=True, null=True)),
                ('abandon_reason', models.TextField(blank=True)),
                ('reconcile_payload', models.JSONField(blank=True, default=dict)),
                ('abandoned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abandoned_historical_race_detail_import_receipts', to=settings.AUTH_USER_MODEL)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_import_receipts', to='stable.historicalbatchrun')),
                ('supersedes_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_receipts', to='stable.historicalracedetailimportreceipt')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['bundle_sha256'], name='hist_rcpt_bundle_idx'), models.Index(fields=['chunk_sha256'], name='hist_rcpt_chunk_idx'), models.Index(fields=['runner', 'status'], name='hist_rcpt_runner_status_idx'), models.Index(fields=['layer', 'status'], name='hist_rcpt_layer_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_count__gt', 0)), name='hist_rcpt_target_count_gt_zero'), models.CheckConstraint(condition=models.Q(('layer__in', ('historical_through_2024', 'current_year_due'))), name='hist_rcpt_layer_valid'), models.CheckConstraint(condition=models.Q(models.Q(('abandon_reason', ''), ('abandoned_at__isnull', True), ('abandoned_by__isnull', True), ('completed_at__isnull', True), ('completion_payload', {}), ('reconcile_payload', {}), ('status', 'started')), models.Q(('abandon_reason', ''), ('abandoned_at__isnull', True), ('abandoned_by__isnull', True), ('completed_at__isnull', False), ('reconcile_payload', {}), ('status', 'completed'), models.Q(('completion_payload', {}), _negated=True)), models.Q(('abandoned_at__isnull', False), ('abandoned_by__isnull', False), ('completed_at__isnull', True), ('completion_payload', {}), ('status', 'abandoned'), models.Q(('abandon_reason', ''), _negated=True), models.Q(('reconcile_payload', {}), _negated=True)), _connector='OR'), name='hist_rcpt_state_consistent')],
            },
        ),
    ]
