# Generated by Django 5.2.1 on 2026-07-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0032_historical_race_detail_import_receipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceEventProjectionControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "write_owner",
                    models.CharField(
                        choices=[
                            ("unmanaged", "未启用"),
                            ("historical", "历史导入"),
                            ("live", "准实时"),
                            ("manual_paused", "人工暂停"),
                        ],
                        default="unmanaged",
                        max_length=16,
                    ),
                ),
                ("owner_generation", models.PositiveBigIntegerField(default=0)),
                ("owner_manifest_sha256", models.CharField(blank=True, max_length=64)),
                ("owner_changed_at", models.DateTimeField(blank=True, null=True)),
                ("next_racecard_revision_no", models.PositiveBigIntegerField(default=1)),
                ("next_result_revision_no", models.PositiveBigIntegerField(default=1)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projection_control",
                        to="stable.raceevent",
                    ),
                ),
                (
                    "owner_changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changed_race_event_projection_controls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("write_owner__in", ("unmanaged", "historical", "live", "manual_paused"))
                        ),
                        name="race_projection_owner_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("next_racecard_revision_no__gte", 1)),
                        name="race_proj_next_card_gte_one",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("next_result_revision_no__gte", 1)),
                        name="race_proj_next_result_gte_one",
                    ),
                ],
            },
        ),
    ]
