# Generated by Django 5.2.1 on 2026-07-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0033_raceeventprojectioncontrol"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceEventLiveTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("scheduled", "已排期"),
                            ("racecard_ready", "出马表已就绪"),
                            ("awaiting_result", "等待赛果"),
                            ("provisional_result", "暂定赛果"),
                            ("official_result", "正式赛果"),
                            ("corrected_result", "改判赛果"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("tracking_enabled", models.BooleanField(default=False)),
                ("next_poll_at", models.DateTimeField(blank=True, null=True)),
                ("window_started_at", models.DateTimeField(blank=True, null=True)),
                ("window_ends_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_observation_hash", models.CharField(blank=True, max_length=64)),
                ("provisional_published_at", models.DateTimeField(blank=True, null=True)),
                ("official_published_at", models.DateTimeField(blank=True, null=True)),
                ("corrected_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("circuit_reason", models.TextField(blank=True)),
                ("stale_at", models.DateTimeField(blank=True, null=True)),
                ("lock_version", models.PositiveBigIntegerField(default=0)),
                ("claim_generation", models.PositiveBigIntegerField(default=0)),
                ("active_attempt_token", models.CharField(blank=True, max_length=64)),
                ("claim_expires_at", models.DateTimeField(blank=True, null=True)),
                ("checkpoint_payload", models.JSONField(blank=True, default=dict)),
                ("source_route_version", models.CharField(blank=True, max_length=64)),
                ("selection_reason", models.TextField(blank=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_tracking",
                        to="stable.raceevent",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tracking_enabled", "next_poll_at"],
                        name="race_track_enabled_poll_idx",
                    ),
                    models.Index(
                        fields=["state", "next_poll_at"],
                        name="race_track_state_poll_idx",
                    ),
                    models.Index(
                        fields=["event", "state"],
                        name="race_track_event_state_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                (
                                    "scheduled",
                                    "racecard_ready",
                                    "awaiting_result",
                                    "provisional_result",
                                    "official_result",
                                    "corrected_result",
                                ),
                            )
                        ),
                        name="race_live_tracking_state_valid",
                    ),
                ],
            },
        ),
    ]
