# Generated by Django 5.2.1 on 2026-07-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0034_raceeventlivetracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceEventParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stable_key", models.CharField(max_length=128)),
                ("canonical_name", models.CharField(max_length=255)),
                ("country_region", models.CharField(blank=True, choices=[("japan", "日本"), ("hong_kong", "中国香港"), ("united_kingdom", "英国"), ("france", "法国"), ("united_states", "美国"), ("other", "其他")], max_length=32)),
                ("birth_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("review_status", models.CharField(choices=[("pending", "待审核"), ("approved", "已批准"), ("rejected", "已拒绝"), ("conflict", "有冲突")], default="pending", max_length=16)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="stable.raceevent")),
                ("horse_profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="race_event_participants", to="stable.horseprofile")),
                ("term", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="race_event_participants", to="stable.termentry")),
            ],
            options={
                "indexes": [models.Index(fields=["event", "review_status"], name="race_part_event_review_idx")],
                "constraints": [models.UniqueConstraint(fields=("event", "stable_key"), name="uq_race_part_event_stable"), models.CheckConstraint(condition=models.Q(("review_status__in", ("pending", "approved", "rejected", "conflict"))), name="race_part_review_valid")],
            },
        ),
        migrations.CreateModel(
            name="RaceResultSourceIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_key", models.CharField(max_length=64)),
                ("external_race_id", models.CharField(max_length=128)),
                ("canonical_url", models.URLField(blank=True)),
                ("host", models.CharField(blank=True, max_length=255)),
                ("identity_fields", models.JSONField(blank=True, default=dict)),
                ("review_status", models.CharField(choices=[("pending", "待审核"), ("approved", "已批准"), ("rejected", "已拒绝"), ("conflict", "有冲突")], default="pending", max_length=16)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("terms_status", models.CharField(choices=[("unknown", "未知"), ("approved", "已批准"), ("manual", "仅人工"), ("blocked", "已阻断")], default="unknown", max_length=16)),
                ("automation_allowed", models.BooleanField(default=False)),
                ("proof_network_allowed", models.BooleanField(default=False)),
                ("evidence_url", models.URLField(blank=True)),
                ("evidence_sha256", models.CharField(blank=True, max_length=64)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("registry_digest", models.CharField(blank=True, max_length=64)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="source_identities", to="stable.raceevent")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reviewed_race_result_source_identities", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [models.Index(fields=["review_status", "terms_status"], name="race_srcid_review_terms_idx")],
                "constraints": [models.UniqueConstraint(fields=("source_key", "external_race_id"), name="uq_race_srcid_source_external"), models.UniqueConstraint(fields=("event", "source_key"), name="uq_race_srcid_event_source"), models.CheckConstraint(condition=models.Q(("review_status__in", ("pending", "approved", "rejected", "conflict"))), name="race_srcid_review_valid"), models.CheckConstraint(condition=models.Q(("terms_status__in", ("unknown", "approved", "manual", "blocked"))), name="race_srcid_terms_valid")],
            },
        ),
        migrations.CreateModel(
            name="RaceEventParticipantSourceIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_runner_id", models.CharField(blank=True, max_length=128)),
                ("participant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="source_identities", to="stable.raceeventparticipant")),
                ("source_identity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participant_identities", to="stable.raceresultsourceidentity")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("participant", "source_identity"), name="uq_race_part_src_identity"), models.UniqueConstraint(condition=models.Q(("external_runner_id", ""), _negated=True), fields=("source_identity", "external_runner_id"), name="uq_race_src_runner_nonblank")],
            },
        ),
    ]
