# Generated by Django 5.2.1 on 2026-07-16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0035_raceliveidentitymodels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceEventRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("racecard", "出马表"), ("result", "赛果")], max_length=16)),
                ("revision_no", models.PositiveBigIntegerField()),
                ("phase", models.CharField(choices=[("racecard", "出马表"), ("provisional", "暂定"), ("official", "正式"), ("corrected", "改判"), ("unknown", "未知")], max_length=16)),
                ("content_sha256", models.CharField(max_length=64)),
                ("source_authority", models.CharField(blank=True, max_length=32)),
                ("decision_reason", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("official_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("conflict_status", models.CharField(choices=[("none", "无冲突"), ("pending", "待处理"), ("resolved", "已解决")], default="none", max_length=16)),
                ("applied_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="applied_race_event_revisions", to=settings.AUTH_USER_MODEL)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="stable.raceevent")),
                ("supersedes", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="superseded_by", to="stable.raceeventrevision")),
            ],
        ),
        migrations.CreateModel(
            name="RaceResultObservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("etag", models.CharField(blank=True, max_length=255)),
                ("last_modified", models.CharField(blank=True, max_length=255)),
                ("parser_version", models.CharField(max_length=64)),
                ("raw_sha256", models.CharField(max_length=64)),
                ("normalized_sha256", models.CharField(max_length=64)),
                ("result_phase", models.CharField(choices=[("racecard", "出马表"), ("provisional", "暂定"), ("official", "正式"), ("corrected", "改判"), ("unknown", "未知")], max_length=16)),
                ("normalized_payload", models.JSONField(blank=True, default=dict)),
                ("field_provenance", models.JSONField(blank=True, default=dict)),
                ("parse_warnings", models.JSONField(blank=True, default=list)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("retryable", models.BooleanField(default=False)),
                ("raw_artifact_path", models.CharField(blank=True, max_length=512)),
                ("raw_size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("retention_until", models.DateTimeField(blank=True, null=True)),
                ("permission_classification", models.CharField(blank=True, max_length=32)),
                ("source_identity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="observations", to="stable.raceresultsourceidentity")),
            ],
        ),
        migrations.CreateModel(
            name="RaceEventRevisionEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(default="supporting", max_length=16)),
                ("revision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence_links", to="stable.raceeventrevision")),
                ("observation", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="revision_evidence_links", to="stable.raceresultobservation")),
            ],
        ),
        migrations.AddField(
            model_name="raceeventrevision",
            name="primary_observation",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="primary_revisions", to="stable.raceresultobservation"),
        ),
        migrations.CreateModel(
            name="RaceEventRevisionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_order", models.PositiveIntegerField(blank=True, null=True)),
                ("internal_order", models.PositiveIntegerField()),
                ("official_finish_position", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("status", models.CharField(choices=[("declared", "已登记"), ("running", "进行中"), ("scratched", "退赛"), ("withdrawn", "取消出走"), ("reinstated", "恢复出走"), ("non_runner", "未出赛"), ("unknown", "未知"), ("finished", "完赛"), ("dead_heat", "并列"), ("disqualified", "失格"), ("did_not_finish", "未完赛"), ("pulled_up", "中止"), ("unseated_rider", "骑师落马"), ("fell", "跌倒"), ("refused", "拒跑")], default="unknown", max_length=24)),
                ("raw_status", models.CharField(blank=True, max_length=64)),
                ("finish_time", models.CharField(blank=True, max_length=64)),
                ("margin", models.CharField(blank=True, max_length=64)),
                ("horse_number", models.CharField(blank=True, max_length=32)),
                ("barrier", models.CharField(blank=True, max_length=32)),
                ("jockey_name", models.CharField(blank=True, max_length=255)),
                ("trainer_name", models.CharField(blank=True, max_length=255)),
                ("carried_weight", models.CharField(blank=True, max_length=64)),
                ("field_provenance", models.JSONField(blank=True, default=dict)),
                ("participant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="revision_items", to="stable.raceeventparticipant")),
                ("revision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="stable.raceeventrevision")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("revision", "participant"), name="uq_race_revitem_revision_part"), models.UniqueConstraint(fields=("revision", "internal_order"), name="uq_race_revitem_revision_order"), models.CheckConstraint(condition=models.Q(("internal_order__gte", 1)), name="race_revitem_order_gte_one"), models.CheckConstraint(condition=models.Q(("status__in", ["declared", "running", "scratched", "withdrawn", "reinstated", "non_runner", "unknown", "finished", "dead_heat", "disqualified", "did_not_finish", "pulled_up", "unseated_rider", "fell", "refused"])), name="race_revitem_status_valid")],
            },
        ),
        migrations.AddIndex(model_name="raceresultobservation", index=models.Index(fields=["source_identity", "-observed_at"], name="race_obs_source_time_idx")),
        migrations.AddIndex(model_name="raceresultobservation", index=models.Index(fields=["result_phase", "observed_at"], name="race_obs_phase_time_idx")),
        migrations.AddConstraint(model_name="raceresultobservation", constraint=models.UniqueConstraint(fields=("source_identity", "normalized_sha256", "result_phase"), name="uq_race_obs_source_hash_phase")),
        migrations.AddConstraint(model_name="raceresultobservation", constraint=models.CheckConstraint(condition=models.Q(("result_phase__in", ["racecard", "provisional", "official", "corrected", "unknown"])), name="race_obs_phase_valid")),
        migrations.AddConstraint(model_name="raceeventrevisionevidence", constraint=models.UniqueConstraint(fields=("revision", "observation"), name="uq_race_rev_evidence_obs")),
        migrations.AddIndex(model_name="raceeventrevision", index=models.Index(fields=["event", "kind", "-revision_no"], name="race_rev_event_kind_no_idx")),
        migrations.AddIndex(model_name="raceeventrevision", index=models.Index(fields=["event", "phase", "-published_at"], name="race_rev_event_phase_pub_idx")),
        migrations.AddConstraint(model_name="raceeventrevision", constraint=models.UniqueConstraint(fields=("event", "kind", "revision_no"), name="uq_race_rev_event_kind_no")),
        migrations.AddConstraint(model_name="raceeventrevision", constraint=models.UniqueConstraint(fields=("event", "kind", "phase", "content_sha256"), name="uq_race_rev_kind_phase_hash")),
        migrations.AddConstraint(model_name="raceeventrevision", constraint=models.CheckConstraint(condition=models.Q(("kind__in", ["racecard", "result"])), name="race_rev_kind_valid")),
        migrations.AddConstraint(model_name="raceeventrevision", constraint=models.CheckConstraint(condition=models.Q(("phase__in", ["racecard", "provisional", "official", "corrected", "unknown"])), name="race_rev_phase_valid")),
        migrations.AddConstraint(model_name="raceeventrevision", constraint=models.CheckConstraint(condition=models.Q(("conflict_status__in", ["none", "pending", "resolved"])), name="race_rev_conflict_valid")),
        migrations.AddConstraint(model_name="raceeventrevision", constraint=models.CheckConstraint(condition=models.Q(("revision_no__gte", 1)), name="race_rev_no_gte_one")),
    ]
