# Generated by Django 5.2.1 on 2026-07-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0036_raceliverevisionmodels"),
    ]

    operations = [
        migrations.AddField(
            model_name="raceeventprojectioncontrol",
            name="current_racecard_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_racecard_projection_controls",
                to="stable.raceeventrevision",
            ),
        ),
        migrations.AddField(
            model_name="raceeventprojectioncontrol",
            name="current_result_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_result_projection_controls",
                to="stable.raceeventrevision",
            ),
        ),
        migrations.AddField(
            model_name="raceeventprojectioncontrol",
            name="last_known_good_racecard_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="last_known_good_racecard_projection_controls",
                to="stable.raceeventrevision",
            ),
        ),
        migrations.AddField(
            model_name="raceeventprojectioncontrol",
            name="last_known_good_result_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="last_known_good_result_projection_controls",
                to="stable.raceeventrevision",
            ),
        ),
    ]
