# Generated by Django 5.2.1 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0037_projectionrevisionpointers"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceLiveHostBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("host", models.CharField(max_length=255, unique=True)),
                ("min_interval_ms", models.PositiveIntegerField(default=1000)),
                ("next_allowed_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("circuit_open_until", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, default="", max_length=64)),
                ("lock_version", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["circuit_open_until", "next_allowed_at"],
                        name="race_host_budget_due_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("host", ""), _negated=True),
                        name="race_host_budget_host_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("min_interval_ms__gte", 1)),
                        name="race_host_budget_interval_gte_one",
                    ),
                ],
            },
        ),
    ]
