# Generated by Django 5.2.1 on 2026-07-16

import django.db.models.deletion
from django.db import migrations, models


REVISION_IMMUTABLE_FUNCTION = "stable_protect_race_revision_identity"
REVISION_PUBLICATION_FUNCTION = "stable_validate_race_revision_publication"
REVISION_PUBLICATION_TRIGGER = "stable_race_revision_publication_guard"
PUBLICATION_REVISION_FUNCTION = "stable_validate_race_publication_revision"
PUBLICATION_REVISION_TRIGGER = "stable_race_publication_revision_guard"


def install_publication_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        f"""
        CREATE OR REPLACE FUNCTION {REVISION_IMMUTABLE_FUNCTION}()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF OLD.event_id IS DISTINCT FROM NEW.event_id
               OR OLD.kind IS DISTINCT FROM NEW.kind
               OR OLD.revision_no IS DISTINCT FROM NEW.revision_no
               OR OLD.phase IS DISTINCT FROM NEW.phase
               OR OLD.content_sha256 IS DISTINCT FROM NEW.content_sha256
               OR OLD.source_authority IS DISTINCT FROM NEW.source_authority
               OR OLD.decision_reason IS DISTINCT FROM NEW.decision_reason
               OR OLD.primary_observation_id IS DISTINCT FROM NEW.primary_observation_id
               OR OLD.supersedes_id IS DISTINCT FROM NEW.supersedes_id
               OR OLD.official_confirmed_at IS DISTINCT FROM NEW.official_confirmed_at
               OR OLD.applied_by_id IS DISTINCT FROM NEW.applied_by_id
               OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
                RAISE EXCEPTION
                    'race event revision identity is immutable for revision %%', OLD.id
                    USING ERRCODE = '23514';
            END IF;

            IF OLD.published_at IS DISTINCT FROM NEW.published_at AND NOT (
                OLD.published_at IS NULL
                AND NEW.published_at IS NOT NULL
                AND EXISTS (
                    SELECT 1
                      FROM stable_raceeventrevisionpublication publication
                     WHERE publication.revision_id = OLD.id
                       AND publication.published_at = NEW.published_at
                )
            ) THEN
                RAISE EXCEPTION
                    'race event revision publication is immutable for revision %%', OLD.id
                    USING ERRCODE = '23514';
            END IF;

            RETURN NEW;
        END;
        $$;
        """
    )
    schema_editor.execute(
        f"""
        CREATE OR REPLACE FUNCTION {REVISION_PUBLICATION_FUNCTION}()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            current_published_at timestamptz;
        BEGIN
            SELECT published_at
              INTO current_published_at
              FROM stable_raceeventrevision
             WHERE id = NEW.id;
            IF NOT FOUND THEN
                RETURN NEW;
            END IF;

            IF current_published_at IS NULL THEN
                IF EXISTS (
                    SELECT 1
                      FROM stable_raceeventrevisionpublication publication
                     WHERE publication.revision_id = NEW.id
                ) THEN
                    RAISE EXCEPTION
                        'unpublished revision has publication audit for revision %%', NEW.id
                        USING ERRCODE = '23514';
                END IF;
            ELSIF NOT EXISTS (
                SELECT 1
                  FROM stable_raceeventrevisionpublication publication
                 WHERE publication.revision_id = NEW.id
                   AND publication.published_at = current_published_at
            ) THEN
                RAISE EXCEPTION
                    'published revision lacks matching publication audit for revision %%', NEW.id
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $$;
        """
    )
    schema_editor.execute(
        f"""
        CREATE CONSTRAINT TRIGGER {REVISION_PUBLICATION_TRIGGER}
        AFTER INSERT OR UPDATE OF published_at
        ON stable_raceeventrevision
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION {REVISION_PUBLICATION_FUNCTION}();
        """
    )
    schema_editor.execute(
        f"""
        CREATE OR REPLACE FUNCTION {PUBLICATION_REVISION_FUNCTION}()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            revision_id bigint;
            revision_published_at timestamptz;
        BEGIN
            revision_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.revision_id ELSE NEW.revision_id END;
            SELECT published_at
              INTO revision_published_at
              FROM stable_raceeventrevision
             WHERE id = revision_id;
            IF NOT FOUND THEN
                RETURN COALESCE(NEW, OLD);
            END IF;
            IF TG_OP = 'DELETE'
               OR revision_published_at IS NULL
               OR revision_published_at IS DISTINCT FROM NEW.published_at THEN
                RAISE EXCEPTION
                    'publication audit does not match revision %%', revision_id
                    USING ERRCODE = '23514';
            END IF;
            RETURN COALESCE(NEW, OLD);
        END;
        $$;
        """
    )
    schema_editor.execute(
        f"""
        CREATE CONSTRAINT TRIGGER {PUBLICATION_REVISION_TRIGGER}
        AFTER INSERT OR UPDATE OR DELETE
        ON stable_raceeventrevisionpublication
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION {PUBLICATION_REVISION_FUNCTION}();
        """
    )


def remove_publication_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        f"DROP TRIGGER IF EXISTS {PUBLICATION_REVISION_TRIGGER} "
        "ON stable_raceeventrevisionpublication;"
    )
    schema_editor.execute(
        f"DROP TRIGGER IF EXISTS {REVISION_PUBLICATION_TRIGGER} "
        "ON stable_raceeventrevision;"
    )
    schema_editor.execute(f"DROP FUNCTION IF EXISTS {PUBLICATION_REVISION_FUNCTION}();")
    schema_editor.execute(f"DROP FUNCTION IF EXISTS {REVISION_PUBLICATION_FUNCTION}();")
    schema_editor.execute(
        f"""
        CREATE OR REPLACE FUNCTION {REVISION_IMMUTABLE_FUNCTION}()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF OLD.event_id IS DISTINCT FROM NEW.event_id
               OR OLD.kind IS DISTINCT FROM NEW.kind
               OR OLD.revision_no IS DISTINCT FROM NEW.revision_no
               OR OLD.phase IS DISTINCT FROM NEW.phase
               OR OLD.content_sha256 IS DISTINCT FROM NEW.content_sha256
               OR OLD.source_authority IS DISTINCT FROM NEW.source_authority
               OR OLD.decision_reason IS DISTINCT FROM NEW.decision_reason
               OR OLD.primary_observation_id IS DISTINCT FROM NEW.primary_observation_id
               OR OLD.supersedes_id IS DISTINCT FROM NEW.supersedes_id
               OR OLD.published_at IS DISTINCT FROM NEW.published_at
               OR OLD.official_confirmed_at IS DISTINCT FROM NEW.official_confirmed_at
               OR OLD.applied_by_id IS DISTINCT FROM NEW.applied_by_id
               OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
                RAISE EXCEPTION
                    'race event revision identity is immutable for revision %%', OLD.id
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $$;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0039_raceliverevisionlinkguards"),
    ]

    operations = [
        migrations.AddField(
            model_name="raceresultsourceidentity",
            name="result_authority",
            field=models.CharField(
                choices=[("supplemental", "补充来源"), ("official", "官方来源")],
                default="supplemental",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="raceresultsourceidentity",
            constraint=models.CheckConstraint(
                condition=models.Q(("result_authority__in", ["supplemental", "official"])),
                name="race_srcid_authority_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="raceresultsourceidentity",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("result_authority", "supplemental"))
                    | models.Q(("review_status", "approved"))
                ),
                name="race_srcid_official_approved",
            ),
        ),
        migrations.CreateModel(
            name="RaceEventRevisionPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=32)),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication",
                        to="stable.raceeventrevision",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            install_publication_guards,
            remove_publication_guards,
        ),
    ]
