# Generated by Django 5.2.1 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0040_raceresultauthority_revisionpublication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raceeventresult",
            name="running_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("declared", "已出走登记"),
                    ("running", "进行中"),
                    ("scratched", "退赛"),
                    ("withdrawn", "取消出走"),
                    ("reinstated", "恢复出走"),
                    ("non_runner", "未出赛"),
                    ("unknown", "未知"),
                    ("finished", "完赛"),
                    ("dead_heat", "并列"),
                    ("disqualified", "失格"),
                    ("did_not_finish", "未完赛"),
                    ("pulled_up", "中止"),
                    ("unseated_rider", "骑师落马"),
                    ("fell", "跌倒"),
                    ("refused", "拒跑"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="raceeventrunner",
            name="running_status",
            field=models.CharField(
                choices=[
                    ("declared", "已出走登记"),
                    ("running", "进行中"),
                    ("scratched", "退赛"),
                    ("withdrawn", "取消出走"),
                    ("reinstated", "恢复出走"),
                    ("non_runner", "未出赛"),
                    ("unknown", "未知"),
                    ("finished", "完赛"),
                    ("dead_heat", "并列"),
                    ("disqualified", "失格"),
                    ("did_not_finish", "未完赛"),
                    ("pulled_up", "中止"),
                    ("unseated_rider", "骑师落马"),
                    ("fell", "跌倒"),
                    ("refused", "拒跑"),
                ],
                default="declared",
                max_length=16,
            ),
        ),
    ]
