# Generated by Django 5.2.1 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0041_extend_race_runner_status_choices"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="raceresultsourceidentity",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(("source_key", "the_racing_api"))
                    | models.Q(("result_authority", "supplemental"))
                ),
                name="race_srcid_tra_supplemental",
            ),
        ),
    ]
