# Generated by Django 5.2.1 on 2026-07-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0042_raceresultsourceidentity_tra_supplemental"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceLivePublicationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("global", "全局"),
                            ("region", "地区"),
                            ("source", "来源"),
                            ("event", "赛事"),
                        ],
                        max_length=16,
                    ),
                ),
                ("scope_key", models.CharField(max_length=255)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("off", "关闭"),
                            ("shadow", "影子运行"),
                            ("provisional_public", "公开暂定赛果"),
                            ("official_public", "公开正式赛果"),
                        ],
                        default="off",
                        max_length=24,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1)),
                (
                    "registry_digest",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "coverage_proof_digest",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope_type", "scope_key"),
                        name="uq_race_live_pub_policy_scope",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "scope_type__in",
                                ["global", "region", "source", "event"],
                            )
                        ),
                        name="race_live_pub_scope_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "mode__in",
                                [
                                    "off",
                                    "shadow",
                                    "provisional_public",
                                    "official_public",
                                ],
                            )
                        ),
                        name="race_live_pub_mode_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="race_live_pub_version_gte1",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RaceLiveEventPublicationAllowlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_key", models.CharField(max_length=64)),
                (
                    "max_mode",
                    models.CharField(
                        choices=[
                            ("off", "关闭"),
                            ("shadow", "影子运行"),
                            ("provisional_public", "公开暂定赛果"),
                            ("official_public", "公开正式赛果"),
                        ],
                        default="off",
                        max_length=24,
                    ),
                ),
                (
                    "coverage_proof_digest",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "official_verification_route",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "official_verification_route_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "official_verification_valid_until",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("version", models.PositiveBigIntegerField(default=1)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_publication_allowlists",
                        to="stable.raceevent",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "source_key"),
                        name="uq_race_live_allow_event_src",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(("source_key", "")),
                        name="race_allow_source_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "max_mode__in",
                                [
                                    "off",
                                    "shadow",
                                    "provisional_public",
                                    "official_public",
                                ],
                            )
                        ),
                        name="race_live_allow_mode_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="race_live_allow_version_gte1",
                    ),
                ],
            },
        ),
    ]
