# Generated by Django 5.2.1 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0043_racelivepublicationcontrols"),
    ]

    operations = [
        migrations.AddField(
            model_name="raceeventrevisionpublication",
            name="allowlist_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="raceeventrevisionpublication",
            name="coverage_proof_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="raceeventrevisionpublication",
            name="policy_versions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="raceeventrevisionpublication",
            name="registry_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="raceeventrevisionpublication",
            constraint=models.CheckConstraint(
                condition=models.Q(("allowlist_version__gte", 1)),
                name="race_pub_allow_version_gte1",
            ),
        ),
    ]
