# Generated by Django 5.2.1 on 2026-07-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0044_raceeventrevisionpublication_policy_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceLiveOfficialMarkerContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country_region",
                    models.CharField(
                        choices=[
                            ("japan", "日本"),
                            ("hong_kong", "中国香港"),
                            ("united_kingdom", "英国"),
                            ("france", "法国"),
                            ("united_states", "美国"),
                            ("other", "其他"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_key", models.CharField(max_length=64)),
                ("parser_version", models.CharField(max_length=64)),
                (
                    "allowed_marker_types",
                    models.JSONField(blank=True, default=list),
                ),
                ("contract_digest", models.CharField(max_length=64)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                            ("conflict", "有冲突"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country_region", "source_key", "parser_version"),
                        name="uq_race_marker_contract_route",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(source_key=""),
                        name="race_marker_contract_src_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(parser_version=""),
                        name="race_marker_contract_parser_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(contract_digest=""),
                        name="race_marker_contract_digest_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            review_status__in=[
                                "pending",
                                "approved",
                                "rejected",
                                "conflict",
                            ]
                        ),
                        name="race_marker_contract_review_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(version__gte=1),
                        name="race_marker_contract_version_gte1",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RaceLiveOfficialMarkerEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("marker_type", models.CharField(max_length=64)),
                ("contract_digest", models.CharField(max_length=64)),
                ("parser_version", models.CharField(max_length=64)),
                ("raw_sha256", models.CharField(max_length=64)),
                ("source_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_rows",
                        to="stable.raceliveofficialmarkercontract",
                    ),
                ),
                (
                    "observation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="official_marker_evidence",
                        to="stable.raceresultobservation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=~models.Q(marker_type=""),
                        name="race_marker_evidence_type_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(contract_digest=""),
                        name="race_marker_evidence_contract_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(parser_version=""),
                        name="race_marker_evidence_parser_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(raw_sha256=""),
                        name="race_marker_evidence_raw_nonempty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RaceLiveOfficialVerificationIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("official_route", models.CharField(max_length=255)),
                ("official_route_version", models.CharField(max_length=64)),
                ("deadline_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "待复核"),
                            ("resolved", "已解决"),
                            ("escalated", "已升级"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("last_probe_at", models.DateTimeField(blank=True, null=True)),
                ("next_probe_at", models.DateTimeField(blank=True, null=True)),
                ("alert_sent_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="official_verification_incidents",
                        to="stable.raceevent",
                    ),
                ),
                (
                    "provisional_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="official_verification_incidents",
                        to="stable.raceeventrevision",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "next_probe_at"],
                        name="race_official_incident_due_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "event",
                            "provisional_revision",
                            "official_route_version",
                        ),
                        name="uq_race_official_incident_route",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(official_route=""),
                        name="race_official_incident_route_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(official_route_version=""),
                        name="race_official_incident_version_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            status__in=["open", "resolved", "escalated"]
                        ),
                        name="race_official_incident_status_valid",
                    ),
                ],
            },
        ),
    ]
