# Generated by Django 5.2.1 on 2026-07-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0046_race_live_manual_verification_contract"),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldataimporterror',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AlterField(
            model_name='externaldataimportlock',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AlterField(
            model_name='externaldataimportrun',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalhorse',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalhorsealias',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalhorsehistory',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalraceentry',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalraceodds',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalraceresult',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalraceeventtarget',
            name='country_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], max_length=32),
        ),
        migrations.AlterField(
            model_name='horsep0source',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AlterField(
            model_name='horseprofile',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AlterField(
            model_name='majorraceevent',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], max_length=32),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source_site',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('jra', 'JRA'), ('sponichi', 'Sponichi'), ('hkjc_news', 'HKJC Racing News'), ('scmp_racing', 'SCMP Racing'), ('sporting_life', 'Sporting Life Racing'), ('sky_sports_racing', 'Sky Sports Racing'), ('bha', 'BHA'), ('france_galop_news', 'France Galop English News'), ('tdn', 'Thoroughbred Daily News'), ('tdn_france', 'TDN France Keyword News'), ('horse_racing_nation', 'Horse Racing Nation'), ('at_the_races', 'At The Races'), ('bloodhorse', 'BloodHorse'), ('paulick_report', 'Paulick Report'), ('hri_news', 'Horse Racing Ireland News'), ('woodbine_news', 'Woodbine News'), ('emirates_racing_authority', 'Emirates Racing Authority'), ('jcsa_news', 'Jockey Club of Saudi Arabia News'), ('racing_victoria_news', 'Racing Victoria News')], max_length=32),
        ),
        migrations.AlterField(
            model_name='newsarticlerelatedregion',
            name='region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], max_length=32),
        ),
        migrations.AlterField(
            model_name='newssnapshot',
            name='source_site',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('jra', 'JRA'), ('sponichi', 'Sponichi'), ('hkjc_news', 'HKJC Racing News'), ('scmp_racing', 'SCMP Racing'), ('sporting_life', 'Sporting Life Racing'), ('sky_sports_racing', 'Sky Sports Racing'), ('bha', 'BHA'), ('france_galop_news', 'France Galop English News'), ('tdn', 'Thoroughbred Daily News'), ('tdn_france', 'TDN France Keyword News'), ('horse_racing_nation', 'Horse Racing Nation'), ('at_the_races', 'At The Races'), ('bloodhorse', 'BloodHorse'), ('paulick_report', 'Paulick Report'), ('hri_news', 'Horse Racing Ireland News'), ('woodbine_news', 'Woodbine News'), ('emirates_racing_authority', 'Emirates Racing Authority'), ('jcsa_news', 'Jockey Club of Saudi Arabia News'), ('racing_victoria_news', 'Racing Victoria News')], max_length=32),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='racing_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], default='japan', max_length=32),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='source_site',
            field=models.CharField(blank=True, choices=[('netkeiba', 'netkeiba'), ('jra', 'JRA'), ('sponichi', 'Sponichi'), ('hkjc_news', 'HKJC Racing News'), ('scmp_racing', 'SCMP Racing'), ('sporting_life', 'Sporting Life Racing'), ('sky_sports_racing', 'Sky Sports Racing'), ('bha', 'BHA'), ('france_galop_news', 'France Galop English News'), ('tdn', 'Thoroughbred Daily News'), ('tdn_france', 'TDN France Keyword News'), ('horse_racing_nation', 'Horse Racing Nation'), ('at_the_races', 'At The Races'), ('bloodhorse', 'BloodHorse'), ('paulick_report', 'Paulick Report'), ('hri_news', 'Horse Racing Ireland News'), ('woodbine_news', 'Woodbine News'), ('emirates_racing_authority', 'Emirates Racing Authority'), ('jcsa_news', 'Jockey Club of Saudi Arabia News'), ('racing_victoria_news', 'Racing Victoria News')], max_length=32),
        ),
        migrations.AlterField(
            model_name='productionwindow',
            name='racing_region',
            field=models.CharField(blank=True, choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], max_length=32),
        ),
        migrations.AlterField(
            model_name='raceevent',
            name='country_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], max_length=32),
        ),
        migrations.AlterField(
            model_name='raceeventparticipant',
            name='country_region',
            field=models.CharField(blank=True, choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], max_length=32),
        ),
        migrations.AlterField(
            model_name='raceliveofficialmarkercontract',
            name='country_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], max_length=32),
        ),
        migrations.AlterField(
            model_name='raceseries',
            name='country_region',
            field=models.CharField(choices=[('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], max_length=32),
        ),
        migrations.AlterField(
            model_name='termentry',
            name='racing_region',
            field=models.CharField(blank=True, choices=[('', '全局通用'), ('japan', '日本'), ('hong_kong', '中国香港'), ('united_kingdom', '英国'), ('france', '法国'), ('united_states', '美国'), ('ireland', '爱尔兰'), ('canada', '加拿大'), ('united_arab_emirates', '阿联酋'), ('saudi_arabia', '沙特阿拉伯'), ('australia', '澳大利亚'), ('other', '其他')], default='', max_length=32),
        ),
    ]
