# Generated by Django 5.2.1 on 2026-07-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0047_alter_externaldataimporterror_racing_region_and_more'),
        ('stable', '0047_race_live_public_beta_controls'),
    ]

    operations = [
    ]
