# Generated by Django 5.2.1 on 2026-07-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0048_merge_20260719_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='source_site',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('jra', 'JRA'), ('sponichi', 'Sponichi'), ('hkjc_news', 'HKJC Racing News'), ('scmp_racing', 'SCMP Racing'), ('sporting_life', 'Sporting Life Racing'), ('sky_sports_racing', 'Sky Sports Racing'), ('bha', 'BHA'), ('france_galop_news', 'France Galop English News'), ('tdn', 'Thoroughbred Daily News'), ('tdn_france', 'TDN France Keyword News'), ('horse_racing_nation', 'Horse Racing Nation'), ('at_the_races', 'At The Races'), ('bloodhorse', 'BloodHorse'), ('paulick_report', 'Paulick Report'), ('hri_news', 'Horse Racing Ireland News'), ('woodbine_news', 'Woodbine News'), ('emirates_racing_authority', 'Emirates Racing Authority'), ('jcsa_news', 'Jockey Club of Saudi Arabia News'), ('racing_victoria_news', 'Racing Victoria News'), ('rte_racing', 'RTÉ Racing'), ('irishracing_news', 'IrishRacing News'), ('canadian_thoroughbred', 'Canadian Thoroughbred'), ('assiniboia_downs_news', 'Assiniboia Downs News'), ('dubai_racing_club', 'Dubai Racing Club'), ('the_national_racing', 'The National Horse Racing'), ('spa_horse_racing', 'Saudi Press Agency Horse Racing'), ('arab_news_racing', 'Arab News Horse Racing'), ('just_horse_racing', 'Just Horse Racing'), ('the_straight', 'The Straight'), ('racing_nsw_news', 'Racing NSW News'), ('tasracing_news', 'Tasracing News')], max_length=32),
        ),
        migrations.AlterField(
            model_name='newssnapshot',
            name='source_site',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('jra', 'JRA'), ('sponichi', 'Sponichi'), ('hkjc_news', 'HKJC Racing News'), ('scmp_racing', 'SCMP Racing'), ('sporting_life', 'Sporting Life Racing'), ('sky_sports_racing', 'Sky Sports Racing'), ('bha', 'BHA'), ('france_galop_news', 'France Galop English News'), ('tdn', 'Thoroughbred Daily News'), ('tdn_france', 'TDN France Keyword News'), ('horse_racing_nation', 'Horse Racing Nation'), ('at_the_races', 'At The Races'), ('bloodhorse', 'BloodHorse'), ('paulick_report', 'Paulick Report'), ('hri_news', 'Horse Racing Ireland News'), ('woodbine_news', 'Woodbine News'), ('emirates_racing_authority', 'Emirates Racing Authority'), ('jcsa_news', 'Jockey Club of Saudi Arabia News'), ('racing_victoria_news', 'Racing Victoria News'), ('rte_racing', 'RTÉ Racing'), ('irishracing_news', 'IrishRacing News'), ('canadian_thoroughbred', 'Canadian Thoroughbred'), ('assiniboia_downs_news', 'Assiniboia Downs News'), ('dubai_racing_club', 'Dubai Racing Club'), ('the_national_racing', 'The National Horse Racing'), ('spa_horse_racing', 'Saudi Press Agency Horse Racing'), ('arab_news_racing', 'Arab News Horse Racing'), ('just_horse_racing', 'Just Horse Racing'), ('the_straight', 'The Straight'), ('racing_nsw_news', 'Racing NSW News'), ('tasracing_news', 'Tasracing News')], max_length=32),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='source_site',
            field=models.CharField(blank=True, choices=[('netkeiba', 'netkeiba'), ('jra', 'JRA'), ('sponichi', 'Sponichi'), ('hkjc_news', 'HKJC Racing News'), ('scmp_racing', 'SCMP Racing'), ('sporting_life', 'Sporting Life Racing'), ('sky_sports_racing', 'Sky Sports Racing'), ('bha', 'BHA'), ('france_galop_news', 'France Galop English News'), ('tdn', 'Thoroughbred Daily News'), ('tdn_france', 'TDN France Keyword News'), ('horse_racing_nation', 'Horse Racing Nation'), ('at_the_races', 'At The Races'), ('bloodhorse', 'BloodHorse'), ('paulick_report', 'Paulick Report'), ('hri_news', 'Horse Racing Ireland News'), ('woodbine_news', 'Woodbine News'), ('emirates_racing_authority', 'Emirates Racing Authority'), ('jcsa_news', 'Jockey Club of Saudi Arabia News'), ('racing_victoria_news', 'Racing Victoria News'), ('rte_racing', 'RTÉ Racing'), ('irishracing_news', 'IrishRacing News'), ('canadian_thoroughbred', 'Canadian Thoroughbred'), ('assiniboia_downs_news', 'Assiniboia Downs News'), ('dubai_racing_club', 'Dubai Racing Club'), ('the_national_racing', 'The National Horse Racing'), ('spa_horse_racing', 'Saudi Press Agency Horse Racing'), ('arab_news_racing', 'Arab News Horse Racing'), ('just_horse_racing', 'Just Horse Racing'), ('the_straight', 'The Straight'), ('racing_nsw_news', 'Racing NSW News'), ('tasracing_news', 'Tasracing News')], max_length=32),
        ),
    ]
