# Generated by Codex on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0048_raceeventrunner_external_runner_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="horseprofile",
            name="career_history_status",
            field=models.CharField(
                choices=[
                    ("not_started", "尚未采集"),
                    ("partial", "部分履历"),
                    ("complete", "完整生涯"),
                    ("needs_review", "需要审核"),
                ],
                default="not_started",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="official_or_source_start_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="collected_start_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="linked_race_event_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="unlinked_race_record_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="overseas_start_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="deduplicated_source_record_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="career_history_gap_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="career_history_gap_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="career_history_source_refs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="horseprofile",
            name="career_history_last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="race_date_precision",
            field=models.CharField(
                choices=[
                    ("exact", "完整日期"),
                    ("month", "精确到月"),
                    ("year", "精确到年"),
                    ("unknown", "未知"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="race_name_normalized",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="race_region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("japan", "日本"),
                    ("hong_kong", "中国香港"),
                    ("united_kingdom", "英国"),
                    ("france", "法国"),
                    ("united_states", "美国"),
                    ("other", "其他"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="race_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="distance_meters",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="race_type_text",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="horse_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="barrier",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="jockey_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="carried_weight",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="finish_time",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="prize_text",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="start_status",
            field=models.CharField(
                choices=[
                    ("started", "实际出赛"),
                    ("did_not_start", "未实际出赛"),
                    ("unconfirmed", "是否出赛待确认"),
                ],
                default="unconfirmed",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="is_overseas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="horseracerecord",
            name="canonical_race_key",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
