# Generated by Django 5.2.1 on 2026-07-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0048_raceeventrunner_external_runner_identity'),
        ('stable', '0049_alter_newsarticle_source_site_and_more'),
    ]

    operations = [
    ]
