# Generated by Django 5.2.1 on 2026-07-24 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0053_newsarticle_publish_ready_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageHeadlineRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(default='homepage_primary', max_length=32)),
                ('status', models.CharField(choices=[('active', '活跃'), ('accepted', '已接受'), ('superseded', '已替换'), ('invalidated', '已失效')], default='active', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('evidence', models.JSONField(default=dict)),
                ('engine_version', models.CharField(max_length=64)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.newsarticle')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['slot', 'status', '-created_at'], name='headline_rec_slot_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('slot', 'homepage_primary')), name='headline_recommendation_slot_check'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('slot',), name='headline_recommendation_unique_active')],
            },
        ),
        migrations.CreateModel(
            name='HomepageHeadlineSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(default='homepage_primary', max_length=32, unique=True)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.newsarticle')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('slot', 'homepage_primary')), name='headline_selection_slot_check')],
            },
        ),
    ]
