# Generated by Django 5.2.1 on 2026-07-24 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0053_newsarticle_publish_ready_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceFieldNormalizationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.PositiveIntegerField(default=0)),
                ('model_label', models.CharField(max_length=64)),
                ('object_pk', models.PositiveIntegerField()),
                ('before_snapshot', models.JSONField(default=dict)),
                ('after_snapshot', models.JSONField(default=dict)),
                ('input_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('race_term_id', models.PositiveIntegerField(blank=True, null=True)),
                ('racecourse_term_id', models.PositiveIntegerField(blank=True, null=True)),
                ('normalizer_version', models.CharField(max_length=64)),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['run', 'batch_number', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RaceFieldNormalizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=32)),
                ('model_scope', models.CharField(max_length=64)),
                ('manifest_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('normalizer_version', models.CharField(max_length=64)),
                ('term_snapshot_digest', models.CharField(blank=True, default='', max_length=64)),
                ('checkpoint_data', models.JSONField(blank=True, default=dict)),
                ('planned_count', models.PositiveIntegerField(default=0)),
                ('actual_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='age_open_ended',
            field=models.BooleanField(default=False, verbose_name='年龄无上限'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='course_layout_text',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='路线'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='distance_meters_normalized',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='规范距离(米)'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='distance_precision',
            field=models.CharField(blank=True, choices=[('official_metric', '官方公制'), ('exact_conversion', '精确换算'), ('approximate_conversion', '近似换算'), ('unknown', '未知')], default='', max_length=32, verbose_name='距离精度'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='eligibility_constraints',
            field=models.JSONField(blank=True, default=dict, verbose_name='资格约束'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='eligibility_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='参赛资格原文'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='going_text',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='场地状况'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='maximum_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最高年龄'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='minimum_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最低年龄'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='normalization_input_sha256',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='规范化输入摘要'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='normalization_issues',
            field=models.JSONField(blank=True, default=list, verbose_name='规范化问题'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='normalization_version',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='规范化版本'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='normalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='规范化时间'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='normalized_finish_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='规范名次'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='normalized_race_type',
            field=models.CharField(blank=True, choices=[('flat', '平地'), ('hurdle', '障碍'), ('steeplechase', '越野障碍'), ('other', '其他'), ('unknown', '未知')], default='', max_length=32, verbose_name='规范赛种'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='normalized_result_status',
            field=models.CharField(blank=True, choices=[('finished', '完赛'), ('dead_heat', '同着'), ('did_not_finish', '未完赛'), ('pulled_up', '拉停'), ('unseated_rider', '落马'), ('fell', '堕马'), ('disqualified', '失格'), ('scratched', '退赛'), ('non_runner', '未出赛'), ('withdrawn', '退出'), ('unknown', '未知')], default='', max_length=32, verbose_name='规范结果状态'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='normalized_surface',
            field=models.CharField(blank=True, choices=[('turf', '草地'), ('dirt', '泥地'), ('synthetic', '合成'), ('unknown', '未知')], default='', max_length=32, verbose_name='规范场地'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='race_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.termentry', verbose_name='赛事术语'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='racecourse_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.termentry', verbose_name='马场术语'),
        ),
        migrations.AddField(
            model_name='horseracerecord',
            name='sex_restriction',
            field=models.CharField(blank=True, choices=[('open', '不限'), ('female', '牝马'), ('male', '牡马'), ('male_or_female', '牡/牝'), ('other', '其他'), ('unknown', '未知')], default='', max_length=32, verbose_name='性别限制'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='age_open_ended',
            field=models.BooleanField(default=False, verbose_name='年龄无上限'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='course_layout_text',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='路线'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='distance_meters_normalized',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='规范距离(米)'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='distance_precision',
            field=models.CharField(blank=True, choices=[('official_metric', '官方公制'), ('exact_conversion', '精确换算'), ('approximate_conversion', '近似换算'), ('unknown', '未知')], default='', max_length=32, verbose_name='距离精度'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='eligibility_constraints',
            field=models.JSONField(blank=True, default=dict, verbose_name='资格约束'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='going_text',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='场地状况'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='maximum_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最高年龄'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='minimum_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最低年龄'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='normalization_input_sha256',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='规范化输入摘要'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='normalization_issues',
            field=models.JSONField(blank=True, default=list, verbose_name='规范化问题'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='normalization_version',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='规范化版本'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='normalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='规范化时间'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='normalized_race_type',
            field=models.CharField(blank=True, choices=[('flat', '平地'), ('hurdle', '障碍'), ('steeplechase', '越野障碍'), ('other', '其他'), ('unknown', '未知')], default='', max_length=32, verbose_name='规范赛种'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='normalized_surface',
            field=models.CharField(blank=True, choices=[('turf', '草地'), ('dirt', '泥地'), ('synthetic', '合成'), ('unknown', '未知')], default='', max_length=32, verbose_name='规范场地'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='racecourse_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.termentry', verbose_name='马场术语'),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='sex_restriction',
            field=models.CharField(blank=True, choices=[('open', '不限'), ('female', '牝马'), ('male', '牡马'), ('male_or_female', '牡/牝'), ('other', '其他'), ('unknown', '未知')], default='', max_length=32, verbose_name='性别限制'),
        ),
        migrations.AddField(
            model_name='racefieldnormalizationreceipt',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='stable.racefieldnormalizationrun'),
        ),
        migrations.AddConstraint(
            model_name='racefieldnormalizationreceipt',
            constraint=models.UniqueConstraint(fields=('run', 'model_label', 'object_pk'), name='unique_normalization_receipt_per_object'),
        ),
    ]
