# Generated by Django 5.2.1 on 2026-07-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0055_race_field_normalization_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horseracerecord',
            name='normalized_result_status',
            field=models.CharField(blank=True, choices=[('finished', '完赛'), ('dead_heat', '同着'), ('did_not_finish', '未完赛'), ('pulled_up', '拉停'), ('brought_down', '拉停(被带倒)'), ('unseated_rider', '落马'), ('fell', '堕马'), ('disqualified', '失格'), ('scratched', '退赛'), ('non_runner', '未出赛'), ('withdrawn', '退出'), ('unknown', '未知')], default='', max_length=32, verbose_name='规范结果状态'),
        ),
    ]
