# Generated by Django 5.2.1 on 2026-07-24 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0054_homepage_headline_control'),
        ('stable', '0056_race_field_normalization_brought_down'),
    ]

    operations = [
    ]
