# Generated by Django 5.2.1 on 2026-07-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0057_merge_20260725_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceEventFieldAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(choices=[('event', '赛事'), ('participant', '参赛马')], max_length=16)),
                ('subject_key', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=64)),
                ('authority_level', models.PositiveSmallIntegerField(default=0)),
                ('source_key', models.CharField(blank=True, max_length=128)),
                ('source_url', models.CharField(blank=True, max_length=1000)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('value_sha256', models.CharField(blank=True, max_length=64)),
                ('manual_lock', models.BooleanField(default=False)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.newsarticle')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.raceeventdatacandidate')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_authorities', to='stable.raceevent')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.raceeventrevision')),
            ],
            options={
                'verbose_name_plural': 'race event field authorities',
                'indexes': [models.Index(fields=['event', 'subject_type', 'subject_key'], name='field_auth_event_subject_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'subject_type', 'subject_key', 'field_name'), name='uq_field_authority_subject_field')],
            },
        ),
        migrations.CreateModel(
            name='RaceEventFieldChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(choices=[('event', '赛事'), ('participant', '参赛马')], max_length=16)),
                ('subject_key', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=64)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('source_key', models.CharField(blank=True, max_length=128)),
                ('source_url', models.CharField(blank=True, max_length=1000)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('authority_level', models.PositiveSmallIntegerField(default=0)),
                ('trigger_task', models.CharField(blank=True, max_length=128)),
                ('run_id', models.CharField(blank=True, max_length=64)),
                ('schedule_generation', models.PositiveBigIntegerField(default=0)),
                ('operation_mode', models.CharField(blank=True, max_length=16)),
                ('applied', models.BooleanField(default=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.newsarticle')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.raceeventdatacandidate')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_changes', to='stable.raceevent')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stable.raceeventrevision')),
            ],
            options={
                'ordering': ('event', 'created_at', 'id'),
                'indexes': [models.Index(fields=['event', 'subject_type', 'subject_key'], name='field_change_event_subject_idx'), models.Index(fields=['event', 'field_name'], name='field_change_event_field_idx')],
            },
        ),
        migrations.CreateModel(
            name='RaceEventLifecycleControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('off', '关闭'), ('shadow', '影子'), ('enforce', '执行')], default='off', max_length=16)),
                ('next_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('schedule_generation', models.PositiveBigIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_result_code', models.CharField(blank=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('last_source_key', models.CharField(blank=True, max_length=128)),
                ('refresh_profile', models.CharField(blank=True, default='', max_length=8)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('claim_token', models.CharField(blank=True, max_length=64)),
                ('claim_generation', models.PositiveBigIntegerField(default=0)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('manual_pause_reason', models.TextField(blank=True)),
                ('enrollment_manifest_sha256', models.CharField(blank=True, max_length=64)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_control', to='stable.raceevent')),
            ],
            options={
                'indexes': [models.Index(fields=['mode', 'next_refresh_at'], name='lifecycle_ctrl_m_refresh_idx')],
            },
        ),
        migrations.CreateModel(
            name='RaceEventLifecycleTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(choices=[('scheduled', '赛前'), ('running', '进行中'), ('finished', '已结束'), ('postponed', '延期'), ('cancelled', '取消')], max_length=16)),
                ('to_status', models.CharField(choices=[('scheduled', '赛前'), ('running', '进行中'), ('finished', '已结束'), ('postponed', '延期'), ('cancelled', '取消')], max_length=16)),
                ('reason_code', models.CharField(max_length=64)),
                ('effective_at', models.DateTimeField()),
                ('source_authority', models.CharField(blank=True, max_length=32)),
                ('source_key', models.CharField(blank=True, max_length=128)),
                ('source_url', models.CharField(blank=True, max_length=1000)),
                ('trigger_task', models.CharField(blank=True, max_length=128)),
                ('run_id', models.CharField(blank=True, max_length=64)),
                ('schedule_generation', models.PositiveBigIntegerField(default=0)),
                ('record_kind', models.CharField(choices=[('proposal', '提案'), ('applied', '已应用')], max_length=16)),
                ('dedupe_key', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('based_on_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_transitions', to='stable.raceeventlifecycletransition')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_transitions', to='stable.raceevent')),
            ],
            options={
                'ordering': ('event', 'effective_at', 'id'),
                'indexes': [models.Index(fields=['event', 'record_kind'], name='lifecycle_trans_event_kind_idx'), models.Index(fields=['event', 'schedule_generation'], name='lifecycle_trans_event_gen_idx')],
                'constraints': [models.UniqueConstraint(fields=('dedupe_key',), name='uq_lifecycle_transition_dedupe_key')],
            },
        ),
    ]
