# Generated by Django 5.2.1 on 2026-07-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0058_add_race_event_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceeventlifecyclecontrol',
            name='manifest_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
