# Generated by Django 5.2.1 on 2026-07-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0059_add_lifecycle_manifest_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermMappingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_kind', models.CharField(max_length=32)),
                ('source_url', models.CharField(blank=True, max_length=1000)),
                ('source_digest', models.CharField(blank=True, max_length=64)),
                ('review_status', models.CharField(default='pending', max_length=16)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('identity_payload', models.JSONField(blank=True, default=dict)),
                ('identity_sha256', models.CharField(blank=True, max_length=64)),
                ('alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapping_evidence', to='stable.termalias')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_evidence', to='stable.termentry')),
            ],
            options={
                'indexes': [models.Index(fields=['term', 'review_status'], name='stable_term_term_id_d828bd_idx'), models.Index(fields=['alias', 'review_status'], name='stable_term_alias_i_2ce433_idx')],
            },
        ),
    ]
