# Generated by Django 5.2.1 on 2026-07-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0059_add_lifecycle_manifest_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceEventProductCanonicalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identity_sha256", models.CharField(max_length=64)),
                ("manifest_sha256", models.CharField(max_length=64)),
                ("approved_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_race_event_canonical_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "canonical_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="canonical_product_sources",
                        to="stable.raceevent",
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deactivated_race_event_canonical_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duplicate_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="canonical_product_links",
                        to="stable.raceevent",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["canonical_event", "is_active"],
                        name="race_canon_event_active_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("duplicate_event",),
                        name="uq_race_canon_duplicate_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("duplicate_event", models.F("canonical_event")),
                            _negated=True,
                        ),
                        name="race_canon_not_self",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("identity_sha256__regex", "^[0-9a-f]{64}$")
                        ),
                        name="race_canon_identity_sha256",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("manifest_sha256__regex", "^[0-9a-f]{64}$")
                        ),
                        name="race_canon_manifest_sha256",
                    ),
                ],
            },
        ),
    ]
