# Generated by Django 5.2.1 on 2026-07-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0060_raceeventproductcanonicallink"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceReferenceCollectionRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_key", models.CharField(max_length=64)),
                ("country_region", models.CharField(choices=[("japan", "日本"), ("hong_kong", "中国香港"), ("united_kingdom", "英国"), ("france", "法国"), ("united_states", "美国"), ("other", "其他")], max_length=32)),
                ("parser_name", models.CharField(max_length=64)),
                ("parser_version", models.CharField(max_length=64)),
                ("scope_manifest_sha256", models.CharField(max_length=64)),
                ("local_date_from", models.DateField(blank=True, null=True)),
                ("local_date_to", models.DateField(blank=True, null=True)),
                ("target_count", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("running", "采集中"), ("finished", "已完成"), ("failed", "失败")], default="running", max_length=16)),
                ("trigger_kind", models.CharField(default="management_command", max_length=32)),
                ("trigger_task_id", models.CharField(blank=True, max_length=128)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("cache_hit_count", models.PositiveIntegerField(default=0)),
                ("matched_count", models.PositiveIntegerField(default=0)),
                ("unmatched_count", models.PositiveIntegerField(default=0)),
                ("ambiguous_count", models.PositiveIntegerField(default=0)),
                ("partial_count", models.PositiveIntegerField(default=0)),
                ("unchanged_count", models.PositiveIntegerField(default=0)),
                ("changed_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("artifact_sha256", models.CharField(max_length=64)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [models.Index(fields=["source_key", "created_at"], name="race_ref_run_source_at_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("scope_manifest_sha256", "artifact_sha256"), name="uq_race_ref_run_manifest_artifact"),
                    models.CheckConstraint(condition=models.Q(models.Q(("country_region", "united_kingdom"), ("source_key", "reference_sporting_life")), models.Q(("country_region", "france"), ("source_key", "reference_zeturf")), models.Q(("country_region", "united_states"), ("source_key", "reference_horse_racing_nation")), _connector="OR"), name="race_ref_run_source_region_ck"),
                    models.CheckConstraint(condition=models.Q(models.Q(("status", "finished"), _negated=True), ("finished_at__isnull", False), _connector="OR"), name="race_ref_run_finished_at_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RaceReferencePayload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_key", models.CharField(max_length=64)),
                ("provider_event_key", models.CharField(max_length=255)),
                ("observation_key", models.CharField(max_length=384)),
                ("payload_sha256", models.CharField(max_length=64)),
                ("structured_payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [models.Index(fields=["source_key", "provider_event_key", "created_at"], name="race_ref_payload_src_evt_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("source_key", "observation_key", "payload_sha256"), name="uq_race_ref_payload_identity_hash"),
                    models.CheckConstraint(condition=models.Q(("source_key__in", ("reference_sporting_life", "reference_zeturf", "reference_horse_racing_nation"))), name="race_ref_payload_source_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RaceReferenceReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_url", models.URLField(max_length=1000)),
                ("final_url", models.URLField(max_length=1000)),
                ("source_observed_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField()),
                ("parser_name", models.CharField(max_length=64)),
                ("parser_version", models.CharField(max_length=64)),
                ("legacy_payload_sha256", models.CharField(max_length=64)),
                ("raw_sha256", models.CharField(max_length=64)),
                ("source_cache_ref", models.CharField(max_length=500)),
                ("provenance_sha256", models.CharField(max_length=64)),
                ("match_status", models.CharField(choices=[("matched", "已匹配"), ("unmatched", "未匹配"), ("ambiguous", "歧义"), ("source_only", "仅来源记录")], max_length=16)),
                ("match_confidence", models.PositiveSmallIntegerField(default=0)),
                ("match_evidence", models.JSONField(blank=True, default=dict)),
                ("event_snapshot", models.JSONField(blank=True, default=dict)),
                ("event_snapshot_sha256", models.CharField(max_length=64)),
                ("classification_version", models.CharField(max_length=64)),
                ("is_partial", models.BooleanField(default=False)),
                ("gap_codes", models.JSONField(blank=True, default=list)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reference_receipts", to="stable.raceevent")),
                ("payload", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="receipts", to="stable.racereferencepayload")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="receipts", to="stable.racereferencecollectionrun")),
            ],
            options={
                "ordering": ("-recorded_at", "-id"),
                "indexes": [models.Index(fields=["event", "recorded_at"], name="race_ref_receipt_event_at_idx"), models.Index(fields=["match_status", "recorded_at"], name="race_ref_receipt_match_at_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("run", "payload"), name="uq_race_ref_receipt_run_payload"),
                    models.CheckConstraint(condition=models.Q(models.Q(("match_status", "matched"), models.Q(("event_snapshot", {}), _negated=True)), models.Q(models.Q(("match_status", "matched"), _negated=True), ("event__isnull", True)), _connector="OR"), name="race_ref_receipt_match_evt_ck"),
                    models.CheckConstraint(condition=models.Q(("match_confidence__lte", 100)), name="race_ref_receipt_conf_ck"),
                ],
            },
        ),
    ]
