# Generated by Django 5.2.1 on 2026-07-26 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0060_add_term_mapping_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceNewsExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('homepage', '首页'), ('qq', 'QQ')], max_length=16)),
                ('scope_key', models.CharField(max_length=128)),
                ('slot', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('waiting', '等待'), ('active', '生效'), ('replaced', '已替换'), ('sent', '已发送'), ('suppressed', '已抑制')], default='waiting', max_length=16)),
                ('angle', models.CharField(choices=[('comprehensive_result', '综合赛果'), ('winner', '胜者'), ('connections', '关系者'), ('runner', '参赛马'), ('analysis', '分析'), ('market', '市场'), ('other', '其他')], default='other', max_length=32)),
                ('policy_version', models.CharField(default='1.0', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('replaced_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_exposures', to='stable.newsarticle')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_exposures', to='stable.qqpushdelivery')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_exposures', to='stable.raceevent')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_exposures', to='stable.racenewsexposure')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'channel', 'scope_key'], name='stable_race_event_i_a4289b_idx'), models.Index(fields=['article', 'channel'], name='stable_race_article_73aeaf_idx'), models.Index(fields=['status', 'lease_expires_at'], name='stable_race_status_32e447_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'channel', 'scope_key', 'article'), name='uq_race_exposure_event_channel_scope_article'), models.UniqueConstraint(condition=models.Q(('channel', 'homepage'), models.Q(('status', 'waiting'), ('status', 'active'), _connector='OR')), fields=('event', 'channel', 'scope_key', 'slot'), name='uq_homepage_exposure_active_slot'), models.UniqueConstraint(condition=models.Q(('channel', 'qq'), models.Q(('status', 'waiting'), ('status', 'active'), ('status', 'sent'), _connector='OR')), fields=('event', 'channel', 'scope_key', 'slot'), name='uq_qq_exposure_active_slot')],
            },
        ),
    ]
