# Generated by Django 5.2.1 on 2026-07-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0062_add_exposure_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermConsistencyManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('term_snapshot_sha256', models.CharField(max_length=64)),
                ('settings_sha256', models.CharField(max_length=64)),
                ('resolver_version', models.CharField(default='1.0.0', max_length=16)),
                ('diffs', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', '待提交'), ('committed', '已提交'), ('rolled_back', '已回滚')], default='pending', max_length=16)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='stable_term_status_01d5e0_idx')],
            },
        ),
    ]
