# Generated by Django 5.2.1 on 2026-07-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0064_add_race_news_exposure'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='racenewsexposure',
            constraint=models.CheckConstraint(condition=models.Q(('slot__in', (1, 2))), name='ck_race_exposure_slot_valid'),
        ),
        migrations.AddConstraint(
            model_name='racenewsexposure',
            constraint=models.CheckConstraint(condition=models.Q(('delivery__isnull', True), ('channel', 'qq'), _connector='OR'), name='ck_race_exposure_delivery_channel'),
        ),
    ]
