# Generated by Django 5.2.1 on 2026-07-31 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_release_a_years_and_public_paths(apps, schema_editor):
    RaceEvent = apps.get_model("stable", "RaceEvent")
    RaceEventPublicPath = apps.get_model("stable", "RaceEventPublicPath")
    database_alias = schema_editor.connection.alias

    RaceEvent.objects.using(database_alias).filter(edition_year__isnull=True).update(
        edition_year=models.F("year")
    )

    pending_paths = []
    events = (
        RaceEvent.objects.using(database_alias)
        .only("id", "year", "slug")
        .order_by("id")
        .iterator(chunk_size=1000)
    )
    for event in events:
        pending_paths.append(
            RaceEventPublicPath(
                event_id=event.id,
                year=event.year,
                slug=event.slug,
                path_kind="canonical",
                reason="release_a_existing_event_backfill",
            )
        )
        if len(pending_paths) >= 1000:
            RaceEventPublicPath.objects.using(database_alias).bulk_create(
                pending_paths,
                batch_size=1000,
            )
            pending_paths = []
    if pending_paths:
        RaceEventPublicPath.objects.using(database_alias).bulk_create(
            pending_paths,
            batch_size=1000,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0066_add_term_consistency_manifest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalraceeventtarget',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalraceeventtarget',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_targets', to='stable.historicalraceeventtarget'),
        ),
        migrations.AddField(
            model_name='historicalraceeventtarget',
            name='supersession_manifest_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='raceevent',
            name='edition_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalraceeventtarget',
            name='resolution_status',
            field=models.CharField(choices=[('pending', '待处理'), ('ready', '可导入'), ('source_unavailable', '来源暂不可得'), ('identity_review_required', '系列身份待审'), ('permanently_unavailable', '永久不可得'), ('imported', '已导入'), ('superseded', '已被替代')], default='pending', max_length=32),
        ),
        migrations.CreateModel(
            name='HistoricalRaceCalendarRepairReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifest_sha256', models.CharField(max_length=64, unique=True)),
                ('approval_sha256', models.CharField(max_length=64)),
                ('action_scope_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('applied', '已应用'), ('verified', '已核验'), ('verification_failed', '核验失败'), ('rolled_back', '已回滚')], default='applied', max_length=24)),
                ('rollback_sha256', models.CharField(max_length=64)),
                ('applied_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('verifier_result_sha256', models.CharField(blank=True, max_length=64)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_race_calendar_repair_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-applied_at', '-id'),
                'indexes': [models.Index(fields=['status', '-applied_at'], name='hist_cal_receipt_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='RaceEventPublicPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=160)),
                ('path_kind', models.CharField(choices=[('canonical', '正式路径'), ('legacy', '历史路径')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=128)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_race_event_public_paths', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_paths', to='stable.raceevent')),
            ],
            options={
                'ordering': ('year', 'slug'),
                'indexes': [models.Index(fields=['event', 'path_kind'], name='race_pub_path_event_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('year', 'slug'), name='uq_race_public_path_year_slug'), models.UniqueConstraint(condition=models.Q(('path_kind', 'canonical')), fields=('event',), name='uq_race_public_path_event_canonical')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRaceCalendarMaintenanceGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('action_scope_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', '生效中'), ('exited', '已退出')], default='active', max_length=16)),
                ('entered_at', models.DateTimeField()),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_historical_race_calendar_gates', to=settings.AUTH_USER_MODEL)),
                ('exited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exited_historical_race_calendar_gates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-entered_at', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('status',), name='uq_hist_cal_one_active_gate')],
            },
        ),
        migrations.RunPython(
            backfill_release_a_years_and_public_paths,
            migrations.RunPython.noop,
        ),
    ]
