# Generated by Django 5.2.1 on 2026-08-29 07:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def set_postgresql_migration_timeouts(apps, schema_editor):
    """限制生产 PostgreSQL DDL 等锁和执行时间；其他数据库保持 no-op。"""

    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SET LOCAL lock_timeout = '5s'")
        cursor.execute("SET LOCAL statement_timeout = '5min'")


def forbid_reverse(apps, schema_editor):
    raise IrreversibleError(
        "0077 contains staging evidence tables and columns; restore a verified "
        "backup instead of reversing this migration."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('stable', '0076_alter_externaldataimporterror_racing_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            set_postgresql_migration_timeouts,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='externalhorse',
            name='breeder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalhorse',
            name='dam_external_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='externalhorse',
            name='damsire_external_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='externalhorse',
            name='damsire_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='externalhorse',
            name='sire_external_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='externaldataimporterror',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('the_racing_api', 'The Racing API'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externaldataimportlock',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('the_racing_api', 'The Racing API'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='externaldataimportrun',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('the_racing_api', 'The Racing API'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalhorse',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('the_racing_api', 'The Racing API'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalhorsealias',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('the_racing_api', 'The Racing API'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalhorsehistory',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('the_racing_api', 'The Racing API'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('the_racing_api', 'The Racing API'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalraceentry',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('the_racing_api', 'The Racing API'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalraceodds',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('the_racing_api', 'The Racing API'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalraceresult',
            name='source',
            field=models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('the_racing_api', 'The Racing API'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], default='netkeiba', max_length=32),
        ),
        migrations.CreateModel(
            name='HorseExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('the_racing_api', 'The Racing API'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], max_length=32)),
                ('namespace', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('observed', '已观测'), ('verified', '已验证'), ('rejected', '已拒绝'), ('retired', '已停用')], default='observed', max_length=16)),
                ('evidence_url', models.URLField(blank=True, max_length=500)),
                ('payload_sha256', models.CharField(blank=True, max_length=64)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('horse_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='stable.horseprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_horse_external_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('source', 'namespace', 'external_id'),
                'indexes': [models.Index(fields=['horse_profile', 'status'], name='horse_ext_identity_profile_idx')],
                'constraints': [
                    models.UniqueConstraint(fields=('source', 'namespace', 'external_id'), name='uq_horse_ext_identity_source_ns_id'),
                    models.CheckConstraint(
                        condition=(
                            ~models.Q(status='verified')
                            | (
                                ~models.Q(evidence_url='')
                                & ~models.Q(payload_sha256='')
                                & models.Q(verified_at__isnull=False)
                                & models.Q(verified_by__isnull=False)
                            )
                        ),
                        name='horse_ext_verified_evidence',
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(payload_sha256='')
                            | models.Q(payload_sha256__regex=r'^[0-9a-f]{64}$')
                        ),
                        name='horse_ext_payload_sha_valid',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='HorseNameVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_text', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('ja', '日文'), ('en', '英文'), ('zh', '中文'), ('zh-hant', '繁体中文'), ('fr', '法语')], max_length=16)),
                ('script', models.CharField(max_length=32)),
                ('name_kind', models.CharField(choices=[('registered', '注册名'), ('official_latin', '官方欧字名'), ('hk_assigned', '香港赛马名'), ('pre_import', '来港前名称'), ('translation', '译名'), ('source_display', '来源展示名')], max_length=32)),
                ('country_suffix', models.CharField(blank=True, max_length=8)),
                ('normalized_strict', models.CharField(max_length=255)),
                ('normalized_loose', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('netkeiba', 'netkeiba'), ('hkjc', 'HKJC'), ('the_racing_api', 'The Racing API'), ('sporting_life', 'Sporting Life'), ('france_galop', 'France Galop'), ('geny_france', 'Geny France'), ('horse_racing_nation', 'Horse Racing Nation')], max_length=32)),
                ('is_official', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('evidence_url', models.URLField(blank=True, max_length=500)),
                ('payload_sha256', models.CharField(blank=True, max_length=64)),
                ('external_horse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_variants', to='stable.externalhorse')),
                ('horse_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_variants', to='stable.horseprofile')),
            ],
            options={
                'ordering': ('normalized_strict', 'source', 'name_kind', 'id'),
                'indexes': [models.Index(fields=['normalized_strict', 'country_suffix'], name='horse_name_variant_strict_idx'), models.Index(fields=['normalized_loose', 'language'], name='horse_name_variant_loose_idx')],
                'constraints': [
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ('horse_profile__isnull', False),
                                ('external_horse__isnull', True),
                            )
                            | models.Q(
                                ('horse_profile__isnull', True),
                                ('external_horse__isnull', False),
                            )
                        ),
                        name='horse_name_variant_exactly_one_entity',
                    ),
                    models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_to__isnull', True), ('valid_from__lte', models.F('valid_to')), _connector='OR'), name='horse_name_variant_valid_range'),
                    models.UniqueConstraint(condition=models.Q(('horse_profile__isnull', False)), fields=('horse_profile', 'source', 'name_kind', 'normalized_strict'), name='uq_horse_name_variant_profile'),
                    models.UniqueConstraint(condition=models.Q(('external_horse__isnull', False)), fields=('external_horse', 'source', 'name_kind', 'normalized_strict'), name='uq_horse_name_variant_external'),
                    models.CheckConstraint(
                        condition=(
                            models.Q(payload_sha256='')
                            | models.Q(payload_sha256__regex=r'^[0-9a-f]{64}$')
                        ),
                        name='horse_name_payload_sha_valid',
                    ),
                ],
            },
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=forbid_reverse,
        ),
    ]
