# Generated by Django 5.2.1 on 2026-09-01

from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


def set_postgresql_migration_timeouts(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SET LOCAL lock_timeout = '5s'")
        cursor.execute("SET LOCAL statement_timeout = '5min'")


def forbid_reverse(apps, schema_editor):
    raise IrreversibleError(
        "0078 preserves provider profile snapshots; restore a verified backup "
        "instead of discarding the column."
    )


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0077_racing_api_horse_identity_staging"),
    ]

    operations = [
        migrations.RunPython(
            set_postgresql_migration_timeouts,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="externalhorse",
            name="profile_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=forbid_reverse,
        ),
    ]
