# Generated by Django 5.2.1 on 2026-09-20 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stable", "0078_externalhorse_profile_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="racedatasyncenrollment",
            name="authority_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="racedatasyncenrollment",
            name="source_set_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="racedatasyncenrollment",
            name="source_set_generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="racedatasyncenrollment",
            name="source_set_manifest",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="RaceDataSyncSourceBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "有效"),
                            ("quarantined", "隔离"),
                            ("retired", "退出"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("capabilities", models.JSONField(default=list)),
                ("route_digest", models.CharField(max_length=64)),
                ("contract_digest", models.CharField(max_length=64)),
                ("proof_digest", models.CharField(max_length=64)),
                (
                    "registry_schema_version",
                    models.PositiveSmallIntegerField(default=3),
                ),
                ("identity_evidence_sha256", models.CharField(max_length=64)),
                ("binding_manifest", models.JSONField(default=dict)),
                ("binding_manifest_sha256", models.CharField(max_length=64)),
                ("valid_until", models.DateTimeField()),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_bindings",
                        to="stable.racedatasyncenrollment",
                    ),
                ),
                (
                    "source_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sync_bindings",
                        to="stable.raceresultsourceidentity",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enrollment", "source_identity"),
                        name="uq_race_sync_binding",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("state__in", ("active", "quarantined", "retired"))
                        ),
                        name="race_sync_binding_state",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RaceEventIdentityKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key_type", models.CharField(max_length=32)),
                ("namespace", models.CharField(max_length=64)),
                ("key_sha256", models.CharField(max_length=64)),
                ("key_payload", models.JSONField()),
                ("evidence", models.JSONField(default=dict)),
                ("matcher_version", models.CharField(max_length=64)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="identity_keys",
                        to="stable.raceevent",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("namespace", "key_sha256"), name="uq_race_identity_key"
                    )
                ],
            },
        ),
    ]
